import React, { createContext, useContext, useState } from 'react';

export type SupportedLanguage = 
  // North Eastern Languages
  | 'as'  // Assamese
  | 'bn'  // Bengali
  | 'mni' // Meitei / Manipuri
  | 'kha' // Khasi
  | 'grt' // Garo
  | 'lus' // Mizo
  | 'brx' // Bodo
  | 'trp' // Kokborok (Tripuri)
  | 'nag' // Nagamese
  | 'ne'  // Nepali (Sikkim / Gorkha)
  // National & Global Languages
  | 'en'  // English
  | 'hi'  // Hindi
  | 'es'  // Spanish
  | 'fr'  // French
  | 'de'  // German
  | 'ar'  // Arabic
  | 'zh'  // Mandarin
  | 'ja'  // Japanese
  | 'ru'  // Russian
  | 'pt'; // Portuguese

export interface LanguageInfo {
  code: SupportedLanguage;
  shortCode: string;
  name: string;
  nativeName: string;
  category: 'northeast' | 'global';
  flag: string;
}

export const SUPPORTED_LANGUAGES: LanguageInfo[] = [
  // North Eastern Languages
  { code: 'as',  shortCode: 'AS', name: 'Assamese',   nativeName: 'অসমীয়া',       category: 'northeast', flag: '🇮🇳' },
  { code: 'bn',  shortCode: 'BN', name: 'Bengali',    nativeName: 'বাংলা',         category: 'northeast', flag: '🇮🇳' },
  { code: 'mni', shortCode: 'MN', name: 'Manipuri',   nativeName: 'মৈতৈলোন্',       category: 'northeast', flag: '🇮🇳' },
  { code: 'kha', shortCode: 'KH', name: 'Khasi',      nativeName: 'Ktien Khasi',   category: 'northeast', flag: '🇮🇳' },
  { code: 'grt', shortCode: 'GA', name: 'Garo',       nativeName: 'A.chik',        category: 'northeast', flag: '🇮🇳' },
  { code: 'lus', shortCode: 'MZ', name: 'Mizo',       nativeName: 'Mizo ṭawng',    category: 'northeast', flag: '🇮🇳' },
  { code: 'brx', shortCode: 'BO', name: 'Bodo',       nativeName: 'बड़ो',          category: 'northeast', flag: '🇮🇳' },
  { code: 'trp', shortCode: 'KO', name: 'Kokborok',   nativeName: 'Kokborok',      category: 'northeast', flag: '🇮🇳' },
  { code: 'nag', shortCode: 'NA', name: 'Nagamese',   nativeName: 'Nagamese',      category: 'northeast', flag: '🇮🇳' },
  { code: 'ne',  shortCode: 'NE', name: 'Nepali',     nativeName: 'नेपाली',        category: 'northeast', flag: '🇳🇵' },

  // Indian & Global Languages
  { code: 'en',  shortCode: 'EN', name: 'English',    nativeName: 'English',       category: 'global', flag: '🌐' },
  { code: 'hi',  shortCode: 'HI', name: 'Hindi',      nativeName: 'हिन्दी',        category: 'global', flag: '🇮🇳' },
  { code: 'es',  shortCode: 'ES', name: 'Spanish',    nativeName: 'Español',       category: 'global', flag: '🇪🇸' },
  { code: 'fr',  shortCode: 'FR', name: 'French',     nativeName: 'Français',      category: 'global', flag: '🇫🇷' },
  { code: 'de',  shortCode: 'DE', name: 'German',     nativeName: 'Deutsch',       category: 'global', flag: '🇩🇪' },
  { code: 'ar',  shortCode: 'AR', name: 'Arabic',     nativeName: 'العربية',       category: 'global', flag: '🇸🇦' },
  { code: 'zh',  shortCode: 'ZH', name: 'Mandarin',   nativeName: '中文',          category: 'global', flag: '🇨🇳' },
  { code: 'ja',  shortCode: 'JA', name: 'Japanese',   nativeName: '日本語',        category: 'global', flag: '🇯🇵' },
  { code: 'ru',  shortCode: 'RU', name: 'Russian',    nativeName: 'Русский',       category: 'global', flag: '🇷🇺' },
  { code: 'pt',  shortCode: 'PT', name: 'Portuguese', nativeName: 'Português',     category: 'global', flag: '🇵🇹' },
];

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  "en": {
    "nav.home": "Home",
    "nav.map": "Map",
    "nav.report": "Report",
    "nav.sync": "Sync",
    "nav.sos": "SOS",
    "header.ops": "Field Ops",
    "header.live": "Live",
    "header.off": "Off",
    "home.designated_corridor": "Designated Transit Corridor",
    "home.no_route": "No route assigned",
    "home.clearance": "Clearance",
    "home.distance": "Distance",
    "home.outbox": "Outbox",
    "home.sector_pass_rate": "Sector pass rate",
    "home.direct_route": "Direct route",
    "home.buffered_updates": "Buffered updates",
    "home.synchronized": "Synchronized",
    "home.queued": "queued",
    "home.engage_navigation": "Engage Corridor Navigation",
    "home.live_speed": "Live Speed",
    "home.altitude": "Barometric Altitude",
    "home.gnss_stream": "GNSS telemetry stream",
    "home.transit_estimate": "Transit Estimate",
    "home.hazards": "Hazards",
    "home.noted": "noted",
    "home.field_feed": "Field Telemetry Feed",
    "home.view_all": "View all",
    "home.no_hazards": "No hazards reported in this sector",
    "home.synced": "Synced",
    "route.planner_title": "Transit Corridor Planner",
    "route.planner_sub": "Resilient Offline Routing & Tactical Maps",
    "route.search_placeholder": "Search Transit Corridor, Depot, or Pass",
    "route.full_map": "Full Map",
    "route.exit_full": "Exit Full",
    "route.verified_hubs": "Verified NER Transit Hubs",
    "route.recenter_gps": "Recenter GPS",
    "route.fit_route": "Fit Route",
    "route.engage_nav": "Engage Navigation",
    "route.calculating": "Calculating Route...",
    "route.route_ready": "Route Ready",
    "route.live_results": "Live Locations Found",
    "report.title": "Field Incident Report",
    "report.subtitle": "Real-time Crowdsourced Hazard Feed",
    "report.active_reporter": "Active Field Reporter",
    "report.fetch_gps": "Fetch Live Device GPS Location",
    "report.locating_gps": "Acquiring Satellite GPS Fix...",
    "report.gps_locked": "Device GPS Locked",
    "report.simulated_gps": "Simulated GPS Active",
    "report.category": "Incident Category",
    "report.severity": "Severity Rating",
    "report.segment": "Road or Corridor Segment",
    "report.report_title": "Report Title",
    "report.observations": "Field Observations / Conditions",
    "report.broadcast": "Broadcast Report Immediately",
    "report.offline_save": "Save to Offline Outbox",
    "report.form_tab": "New Report",
    "report.history_tab": "Field History",
    "sos.title": "Distress Transponder",
    "sos.subtitle": "Encrypted High-Priority Emergency Broadcast",
    "sos.operator": "Distress Operator",
    "sos.hold_prompt": "Hold for 2 seconds to broadcast SOS",
    "sos.active_status": "DISTRESS BEACON BROADCASTING",
    "sos.cancel_beacon": "Cancel Distress Beacon (False Alarm)",
    "sos.medical": "Medical Priority",
    "sos.breakdown": "Vehicle Breakdown",
    "sos.threat": "Route Obstacle / Threat",
    "sync.title": "Offline Sync Center",
    "sync.subtitle": "Resilient Store-and-Forward Telemetry",
    "sync.sync_now": "Sync All Records Now",
    "sync.all_synced": "All records synchronized with base",
    "sync.pending_records": "records in buffer",
    "sos.beacon_live": "Distress Transponder Live",
    "sos.broadcasting_telemetry": "Broadcasting Emergency Telemetry",
    "sos.transmitting_desk": "Real-time satellite coordinates transmitting to Operations Desk",
    "sos.beacon_id": "Beacon ID",
    "sos.assigned_unit": "Assigned Unit",
    "sos.sector_role": "Sector / Role",
    "sos.coordinates": "Coordinates",
    "sos.accuracy_radius": "Accuracy Radius",
    "sos.packet_tx": "Packet Transmissions",
    "sos.safety_protocol": "Safety Protocol · Emergency Link",
    "sos.standby": "STANDBY",
    "sos.protocol_desc": "In case of critical road hazard, vehicle incapacitation, or medical distress, engage the emergency transponder.",
    "sos.conditions_title": "Distress Conditions (Optional)",
    "sos.hold_warning": "2-second hold required to prevent accidental activations",
    "sync.radio_mode": "Radio Transceiver Mode",
    "sync.uplink_controller": "Telemetry Uplink Controller",
    "sync.auto_adaptive": "Auto (Adaptive)",
    "sync.manual_override": "Manual Override",
    "sync.rtk_uplink": "Live RTK Uplink",
    "sync.mesh_network": "High-Latency Mesh",
    "sync.airgap_protocol": "Airgap Protocol",
    "sync.outbox_pipeline": "Outbox Pipeline",
    "sync.reports_queued": "Reports Queued",
    "sync.outbox_cleared": "Outbox Cleared",
    "sync.last_synced": "Last synced",
    "sync.local_cache": "Local IndexedDB Cache",
    "sync.map_sectors": "Map Sectors",
    "sync.reports": "Reports",
    "sync.breadcrumbs": "Breadcrumbs",
    "sync.outbox_buffer": "Outbox Buffer",
    "sync.total_entries": "total entries",
    "sync.empty_outbox": "Outbox is empty"
  },
  "as": {
    "nav.home": "গৃহ",
    "nav.map": "মানচিত্ৰ",
    "nav.report": "প্ৰতিবেদন",
    "nav.sync": "সংমিশ্ৰণ",
    "nav.sos": "জৰুৰী",
    "header.ops": "ক্ষেত্ৰ অভিযান",
    "header.live": "অনলাইন",
    "header.off": "অফলাইন",
    "home.designated_corridor": "নিৰ্ধাৰিত পৰিবহন কৰিডৰ",
    "home.no_route": "কোনো পথ নিৰ্ধাৰণ কৰা নাই",
    "home.clearance": "সুৰক্ষা",
    "home.distance": "দূৰত্ব",
    "home.outbox": "আউটবক্স",
    "home.sector_pass_rate": "ক্ষেত্ৰ উত্তীৰ্ণ হাৰ",
    "home.direct_route": "পোনপটীয়া পথ",
    "home.buffered_updates": "সংৰক্ষিত তথ্য",
    "home.synchronized": "সংমিশ্ৰিত",
    "home.queued": "অপেক্ষাৰত",
    "home.engage_navigation": "পথ নিৰ্দেশনা আৰম্ভ কৰক",
    "home.live_speed": "প্ৰকৃত গতি",
    "home.altitude": "উচ্চতা",
    "home.gnss_stream": "উপগ্ৰহ সংকেত",
    "home.transit_estimate": "আনুমানিক সময়",
    "home.hazards": "বিপদ",
    "home.noted": "নথিভুক্ত",
    "home.field_feed": "ক্ষেত্ৰ তথ্য প্ৰবাহ",
    "home.view_all": "সকলো চাওক",
    "home.no_hazards": "কোনো বিপদ পোৱা হোৱা নাই",
    "home.synced": "সংমিশ্ৰিত",
    "route.planner_title": "পৰিবহন কৰিডৰ পৰিকল্পনা",
    "route.planner_sub": "অফলাইন নেভিগেচন আৰু মানচিত্ৰ",
    "route.search_placeholder": "কৰিডৰ, ডিপো বা পাছ সন্ধান কৰক",
    "route.full_map": "সম্পূৰ্ণ মানচিত্ৰ",
    "route.exit_full": "প্ৰস্থান",
    "route.verified_hubs": "যাচাইকৃত কৌশলগত কেন্দ্ৰসমূহ",
    "route.recenter_gps": "কেন্দ্ৰীকৰণ",
    "route.fit_route": "সম্পূৰ্ণ পথ চাওক",
    "route.engage_nav": "পথ আৰম্ভ কৰক",
    "route.calculating": "পথ গণনা কৰা হৈছে...",
    "route.route_ready": "পথ সাজু",
    "route.live_results": "সন্ধান লাভ স্থানসমূহ",
    "report.title": "ক্ষেত্ৰ ঘটনা প্ৰতিবেদন",
    "report.subtitle": "প্ৰত্যক্ষ বিপদ তথ্য",
    "report.active_reporter": "সক্ৰিয় প্ৰতিবেদনকাৰী",
    "report.fetch_gps": "প্ৰকৃত জিপিএছ স্থান লওক",
    "report.locating_gps": "জিপিএছ সংযোগ স্থাপন হৈ আছে...",
    "report.gps_locked": "উপগ্ৰহ জিপিএছ লক্",
    "report.simulated_gps": "অনুকৰণ জিপিএছ সক্ৰিয়",
    "report.category": "ঘটনাৰ ধৰণ",
    "report.severity": "বিপদ মাত্ৰা",
    "report.segment": "পথ বা কৰিডৰ খণ্ড",
    "report.report_title": "প্ৰতিবেদনৰ শিৰোনাম",
    "report.observations": "ক্ষেত্ৰ পৰ্যবেক্ষণ",
    "report.broadcast": "তাৎক্ষণিকভাৱে প্ৰেৰণ কৰক",
    "report.offline_save": "অফলাইন সংৰক্ষণ কৰক",
    "report.form_tab": "নতুন প্ৰতিবেদন",
    "report.history_tab": "ইতিহাস",
    "sos.title": "জৰুৰী বিপদ সংকেত",
    "sos.subtitle": "উচ্চ অগ্ৰাধিকাৰ জৰুৰী সম্প্ৰচাৰ",
    "sos.operator": "সংকেত প্ৰেৰক",
    "sos.hold_prompt": "বিপদ সংকেত প্ৰেৰণৰ বাবে ২ চেকেণ্ড ধৰি ৰাখক",
    "sos.active_status": "বিপদ সংকেত সম্প্ৰচাৰ হৈ আছে",
    "sos.cancel_beacon": "সংকেত বাতিল কৰক (মিছা সংকেত)",
    "sos.medical": "চিকিৎসা প্ৰয়োজনীয়তা",
    "sos.breakdown": "বাহনৰ বিজুতি",
    "sos.threat": "পথৰ বাধা / সংকট",
    "sync.title": "অফলাইন সংমিশ্ৰণ কেন্দ্ৰ",
    "sync.subtitle": "সংৰক্ষণ আৰু প্ৰেৰণ ব্যৱস্থা",
    "sync.sync_now": "সকলো তথ্য এতিয়াই সংমিশ্ৰণ কৰক",
    "sync.all_synced": "সকলো তথ্য মূল কেন্দ্ৰৰ সৈতে সংমিশ্ৰিত",
    "sync.pending_records": "টা তথ্য বাকী আছে",
    "sos.beacon_live": "জৰুৰী বিপদ সংকেত সক্ৰিয়",
    "sos.broadcasting_telemetry": "জৰুৰী টেলিমিত্ৰি সম্প্ৰচাৰ হৈ আছে",
    "sos.transmitting_desk": "নিয়ন্ত্ৰণ কেন্দ্ৰলৈ উপগ্ৰহ স্থানাঙ্ক প্ৰেৰণ হৈ আছে",
    "sos.beacon_id": "সংকেত আইডি",
    "sos.assigned_unit": "নিযুক্ত ইউনিট",
    "sos.sector_role": "খণ্ড / ভূমিকা",
    "sos.coordinates": "স্থানাঙ্ক",
    "sos.accuracy_radius": "সঠিকতা ব্যাসাৰ্ধ",
    "sos.packet_tx": "পেকেট প্ৰেৰণ",
    "sos.safety_protocol": "সুৰক্ষা প্ৰটোকল · জৰুৰী সংযোগ",
    "sos.standby": "অপেক্ষাৰত",
    "sos.protocol_desc": "পথৰ বিপদ, বাহনৰ যন্ত্ৰাংশ বিকল বা চিকিৎসা জৰুৰীকালীন অৱস্থাত জৰুৰী সংকেত অন কৰক।",
    "sos.conditions_title": "বিপদ পৰিস্থিতি (ঐচ্ছিক)",
    "sos.hold_warning": "ভুলবশতঃ সক্ৰিয় নহ'বলৈ ২ চেকেণ্ড ধৰি ৰাখিব লাগিব",
    "sync.radio_mode": "ৰেডিঅ' সংকেত মোড",
    "sync.uplink_controller": "টেলিমিত্ৰি আপলিংক নিয়ন্ত্ৰক",
    "sync.auto_adaptive": "স্বয়ংক্ৰিয় (উপযোগী)",
    "sync.manual_override": "হাতেৰে নিয়ন্ত্ৰণ",
    "sync.rtk_uplink": "প্ৰত্যক্ষ আৰটিকে আপলিংক",
    "sync.mesh_network": "মেশ নেটৱৰ্ক",
    "sync.airgap_protocol": "সম্পূৰ্ণ অফলাইন মোড",
    "sync.outbox_pipeline": "আউটবক্স প্ৰেৰণ তালিকা",
    "sync.reports_queued": "প্ৰতিবেদন অপেক্ষাৰত",
    "sync.outbox_cleared": "আউটবক্স খালী",
    "sync.last_synced": "শেষবাৰ সংমিশ্ৰিত",
    "sync.local_cache": "স্থানীয় সংৰক্ষিত তথ্য",
    "sync.map_sectors": "মানচিত্ৰ খণ্ড",
    "sync.reports": "প্ৰতিবেদনসমূহ",
    "sync.breadcrumbs": "গতিপথ চিন",
    "sync.outbox_buffer": "প্ৰেৰণ বাফাৰ",
    "sync.total_entries": "মুঠ প্ৰৱেশ",
    "sync.empty_outbox": "আউটবক্স খালী"
  },
  "bn": {
    "nav.home": "হোম",
    "nav.map": "মানচিত্র",
    "nav.report": "রিপোর্ট",
    "nav.sync": "সিঙ্ক",
    "nav.sos": "জরুরি",
    "header.ops": "ফিল্ড অপস",
    "header.live": "লাইভ",
    "header.off": "অফ",
    "home.designated_corridor": "নির্ধারিত পরিবহন করিডোর",
    "home.no_route": "কোনো রুট নির্ধারিত নেই",
    "home.clearance": "ছাড়পত্র",
    "home.distance": "দূরত্ব",
    "home.outbox": "আউটবক্স",
    "home.sector_pass_rate": "সেক্টর পাস রেট",
    "home.direct_route": "সরাসরি রুট",
    "home.buffered_updates": "বাফার আপডেট",
    "home.synchronized": "সিঙ্ক্রোনাইজড",
    "home.queued": "অপেক্ষমাণ",
    "home.engage_navigation": "করিডোর নেভিগেশন শুরু করুন",
    "home.live_speed": "বর্তমান গতি",
    "home.altitude": "উচ্চতা",
    "home.gnss_stream": "জিএনএসএস স্ট্রিম",
    "home.transit_estimate": "আনুমানিক সময়",
    "home.hazards": "বিপদসমূহ",
    "home.noted": "নোটকৃত",
    "home.field_feed": "ফিল্ড টেলিমেট্রি ফিড",
    "home.view_all": "সব দেখুন",
    "home.no_hazards": "এই সেক্টরে কোনো বিপদ নেই",
    "home.synced": "সিঙ্কড",
    "route.planner_title": "ট্রানজিট করিডোর প্ল্যানার",
    "route.planner_sub": "অফলাইন রাউটিং ও কৌশলগত মানচিত্র",
    "route.search_placeholder": "করিডোর, ডিপো বা পাস অনুসন্ধান করুন",
    "route.full_map": "পূর্ণ মানচিত্র",
    "route.exit_full": "প্রস্থান",
    "route.verified_hubs": "যাচাইকৃত কৌশলগত হাবসমূহ",
    "route.recenter_gps": "জিপিএস কেন্দ্রীভূত",
    "route.fit_route": "সম্পূর্ণ রুট ফিট",
    "route.engage_nav": "নেভিগেশন শুরু",
    "route.calculating": "রুট গণনা চলছে...",
    "route.route_ready": "রুট প্রস্তুত",
    "route.live_results": "লাইভ অবস্থানসমূহ",
    "report.title": "ফিল্ড ঘটনা রিপোর্ট",
    "report.subtitle": "রিয়েল-টাইম বিপদ ফিড",
    "report.active_reporter": "সক্রিয় ফিল্ড রিপোর্টার",
    "report.fetch_gps": "লাইভ জিপিএস অবস্থান পান",
    "report.locating_gps": "স্যাটেলাইট জিপিএস সন্ধান চলছে...",
    "report.gps_locked": "ডিভাইস জিপিএস লকড",
    "report.simulated_gps": "সিমুলেটেড জিপিএস সক্রিয়",
    "report.category": "ঘটনার বিভাগ",
    "report.severity": "তীব্রতা রেটিং",
    "report.segment": "রাস্তা বা করিডোর অংশ",
    "report.report_title": "রিপোর্টের শিরোনাম",
    "report.observations": "ফিল্ড পর্যবেক্ষণ",
    "report.broadcast": "অবিলম্বে রিপোর্ট পাঠান",
    "report.offline_save": "অফলাইন আউটবক্সে সংরক্ষণ",
    "report.form_tab": "নতুন রিপোর্ট",
    "report.history_tab": "ইতিহাস",
    "sos.title": "জরুরি সংকেত ট্রান্সপন্ডার",
    "sos.subtitle": "এনক্রিপ্ট করা জরুরি ব্রডকাস্ট",
    "sos.operator": "সংকেত প্রেরক",
    "sos.hold_prompt": "সম্প্রচারের জন্য ২ সেকেন্ড চেপে ধরে রাখুন",
    "sos.active_status": "জরুরি সংকেত সম্প্রচারিত হচ্ছে",
    "sos.cancel_beacon": "সংকেত বাতিল করুন (ভুল অ্যালার্ম)",
    "sos.medical": "চিকিৎসা অগ্রাধিকার",
    "sos.breakdown": "যানবাহন বিকল",
    "sos.threat": "রাস্তার বাধা / হুমকি",
    "sync.title": "অফলাইন সিঙ্ক সেন্টার",
    "sync.subtitle": "স্টোর-অ্যান্ড-ফরওয়ার্ড টেলিমেট্রি",
    "sync.sync_now": "এখনই সব সিঙ্ক করুন",
    "sync.all_synced": "সমস্ত রেকর্ড বেসের সাথে সিঙ্কড",
    "sync.pending_records": "টি রেকর্ড বাফারে আছে",
    "sos.beacon_live": "জরুরী ট্রানসপন্ডার সক্রিয়",
    "sos.broadcasting_telemetry": "জরুরী টেলিমেট্রি সম্প্রচার হচ্ছে",
    "sos.transmitting_desk": "অপারেশন ডেস্কে উপগ্রহ স্থানাঙ্ক পাঠানো হচ্ছে",
    "sos.beacon_id": "বীকন আইডি",
    "sos.assigned_unit": "নিযুক্ত ইউনিট",
    "sos.sector_role": "সেক্টর / ভূমিকা",
    "sos.coordinates": "স্থানাঙ্ক",
    "sos.accuracy_radius": "নির্ভুলতার ব্যাসার্ধ",
    "sos.packet_tx": "প্যাকেট সম্প্রচার",
    "sos.safety_protocol": "সুরক্ষা প্রোটোকল · জরুরি লিঙ্ক",
    "sos.standby": "স্ট্যান্ডবাই",
    "sos.protocol_desc": "রাস্তার বিপদ, গাড়ির যান্ত্রিক গোলযোগ বা চিকিৎসা জরুরী পরিস্থিতিতে ট্রান্সপন্ডার সক্রিয় করুন।",
    "sos.conditions_title": "বিপদ পরিস্থিতি (ঐচ্ছিক)",
    "sos.hold_warning": "ভুল সক্রিয়তা রোধ করতে ২ সেকেন্ড ধরে রাখুন",
    "sync.radio_mode": "রেডিও ট্রান্সসিভার মোড",
    "sync.uplink_controller": "টেলিমেট্রি আপলিংক নিয়ন্ত্রক",
    "sync.auto_adaptive": "স্বয়ংক্রিয় (অভিযোজিত)",
    "sync.manual_override": "ম্যানুয়াল নিয়ন্ত্রণ",
    "sync.rtk_uplink": "লাইভ আরটিকে আপলিংক",
    "sync.mesh_network": "মেশ নেটওয়ার্ক",
    "sync.airgap_protocol": "সম্পূর্ণ অফলাইন প্রোটোকল",
    "sync.outbox_pipeline": "আউটবক্স পাইপলাইন",
    "sync.reports_queued": "রিপোর্ট অপেক্ষারত",
    "sync.outbox_cleared": "আউটবক্স খালি",
    "sync.last_synced": "সর্বশেষ সিঙ্ক",
    "sync.local_cache": "স্থানীয় IndexedDB ক্যাশ",
    "sync.map_sectors": "মানচিত্র সেক্টর",
    "sync.reports": "রিপোর্টসমূহ",
    "sync.breadcrumbs": "পথচিহ্ন",
    "sync.outbox_buffer": "আউটবক্স বাফার",
    "sync.total_entries": "মোট এন্ট্রি",
    "sync.empty_outbox": "আউটবক্স খালি"
  },
  "hi": {
    "nav.home": "होम",
    "nav.map": "मानचित्र",
    "nav.report": "रिपोर्ट",
    "nav.sync": "सिंक",
    "nav.sos": "एसओएस",
    "header.ops": "फील्ड ऑप्स",
    "header.live": "लाइव",
    "header.off": "ऑफलाइन",
    "home.designated_corridor": "निर्धारित ट्रांजिट कॉरिडोर",
    "home.no_route": "कोई मार्ग निर्दिष्ट नहीं",
    "home.clearance": "निकासी",
    "home.distance": "दूरी",
    "home.outbox": "आउटबॉक्स",
    "home.sector_pass_rate": "सेक्टर पास दर",
    "home.direct_route": "सीधा मार्ग",
    "home.buffered_updates": "सुरक्षित अपडेट",
    "home.synchronized": "सिंक्रनाइज़्ड",
    "home.queued": "कतारबद्ध",
    "home.engage_navigation": "कॉरिडोर नेविगेशन शुरू करें",
    "home.live_speed": "लाइव गति",
    "home.altitude": "बैरोमीटर ऊंचाई",
    "home.gnss_stream": "जीएनएसएस स्ट्रीम",
    "home.transit_estimate": "पारगमन अनुमान",
    "home.hazards": "खतरे",
    "home.noted": "दर्ज",
    "home.field_feed": "फील्ड टेलीमेट्री फीड",
    "home.view_all": "सभी देखें",
    "home.no_hazards": "इस सेक्टर में कोई खतरा नहीं",
    "home.synced": "सिंक हुआ",
    "route.planner_title": "ट्रांजिट कॉरिडोर प्लानर",
    "route.planner_sub": "ऑफलाइन रूटिंग और सामरिक मानचित्र",
    "route.search_placeholder": "कॉरिडोर, डिपो या दर्रा खोजें",
    "route.full_map": "पूर्ण मानचित्र",
    "route.exit_full": "पूर्ण दृश्य से बाहर",
    "route.verified_hubs": "सत्यापित सामरिक केंद्र",
    "route.recenter_gps": "जीपीएस केंद्रित करें",
    "route.fit_route": "पूरा मार्ग देखें",
    "route.engage_nav": "नेविगेशन शुरू करें",
    "route.calculating": "मार्ग गणना जारी है...",
    "route.route_ready": "मार्ग तैयार",
    "route.live_results": "वास्तविक स्थान प्राप्त",
    "report.title": "फील्ड घटना रिपोर्ट",
    "report.subtitle": "रीयल-टाइम संकट फीड",
    "report.active_reporter": "सक्रिय फील्ड रिपोर्टर",
    "report.fetch_gps": "लाइव डिवाइस जीपीएस स्थिति प्राप्त करें",
    "report.locating_gps": "उपग्रह जीपीएस सिग्नल खोज रहा है...",
    "report.gps_locked": "डिवाइस जीपीएस लॉक सक्रिय",
    "report.simulated_gps": "सिम्युलेटेड जीपीएस सक्रिय",
    "report.category": "घटना श्रेणी",
    "report.severity": "गंभीरता रेटिंग",
    "report.segment": "सड़क या कॉरिडोर खंड",
    "report.report_title": "रिपोर्ट शीर्षक",
    "report.observations": "फील्ड अवलोकन / स्थिति",
    "report.broadcast": "त्वरित रिपोर्ट प्रसारित करें",
    "report.offline_save": "ऑफलाइन आउटबॉक्स में सहेजें",
    "report.form_tab": "नई रिपोर्ट",
    "report.history_tab": "फील्ड इतिहास",
    "sos.title": "संकट ट्रांसपोंडर",
    "sos.subtitle": "एन्क्रिप्टेड उच्च-प्राथमिकता आपातकालीन प्रसारण",
    "sos.operator": "संकट ऑपरेटर",
    "sos.hold_prompt": "प्रसारण के लिए 2 सेकंड दबाकर रखें",
    "sos.active_status": "संकट संकेत प्रसारित हो रहा है",
    "sos.cancel_beacon": "संकट संकेत रद्द करें (गलत अलार्म)",
    "sos.medical": "चिकित्सा प्राथमिकता",
    "sos.breakdown": "वाहन खराबी",
    "sos.threat": "मार्ग बाधा / खतरा",
    "sync.title": "ऑफलाइन सिंक केंद्र",
    "sync.subtitle": "स्टोर-एंड-फॉरवर्ड टेलीमेट्री",
    "sync.sync_now": "सभी रिकॉर्ड अभी सिंक करें",
    "sync.all_synced": "सभी रिकॉर्ड बेस के साथ सिंक्रनाइज़्ड हैं",
    "sync.pending_records": "रिकॉर्ड कतार में हैं",
    "sos.beacon_live": "आपातकालीन ट्रांसपोंडर सक्रिय",
    "sos.broadcasting_telemetry": "आपातकालीन टेलीमेट्री प्रसारित हो रही है",
    "sos.transmitting_desk": "ऑपरेशंस डेस्क पर रीयल-टाइम उपग्रह निर्देशांक भेजे जा रहे हैं",
    "sos.beacon_id": "बीकन आईडी",
    "sos.assigned_unit": "आवंटित यूनिट",
    "sos.sector_role": "क्षेत्र / भूमिका",
    "sos.coordinates": "निर्देशांक",
    "sos.accuracy_radius": "सटीकता दायरा",
    "sos.packet_tx": "पैकेट प्रसारण",
    "sos.safety_protocol": "सुरक्षा प्रोटोकॉल · आपातकालीन लिंक",
    "sos.standby": "स्टैंडबाय",
    "sos.protocol_desc": "सड़क खतरे, वाहन खराबी या चिकित्सा संकट के मामले में आपातकालीन ट्रांसपोंडर सक्रिय करें।",
    "sos.conditions_title": "संकट स्थितियां (वैकल्पिक)",
    "sos.hold_warning": "गलती से सक्रिय होने से रोकने के लिए 2 सेकंड दबाकर रखें",
    "sync.radio_mode": "रेडियो ट्रांससीवर मोड",
    "sync.uplink_controller": "टेलीमेट्री अपलिंक नियंत्रक",
    "sync.auto_adaptive": "स्वचालित (अनुकूली)",
    "sync.manual_override": "मैन्युअल नियंत्रण",
    "sync.rtk_uplink": "लाइव आरटीके अपलिंक",
    "sync.mesh_network": "मेश नेटवर्क (धीमा)",
    "sync.airgap_protocol": "एयरगैप प्रोटोकॉल (पूर्ण ऑफलाइन)",
    "sync.outbox_pipeline": "आउटबॉक्स पाइपलाइन",
    "sync.reports_queued": "रिपोर्ट कतारबद्ध",
    "sync.outbox_cleared": "आउटबॉक्स खाली है",
    "sync.last_synced": "अंतिम सिंक",
    "sync.local_cache": "स्थानीय IndexedDB कैश",
    "sync.map_sectors": "मानचित्र क्षेत्र",
    "sync.reports": "रिपोर्ट्स",
    "sync.breadcrumbs": "पथ निशान (Breadcrumbs)",
    "sync.outbox_buffer": "आउटबॉक्स बफ़र",
    "sync.total_entries": "कुल प्रविष्टियां",
    "sync.empty_outbox": "आउटबॉक्स खाली है"
  },
  "mni": {
    "nav.home": "য়ুম্বী",
    "nav.map": "মানচিত্র",
    "nav.report": "পাউদম",
    "nav.sync": "পুন্সিনবা",
    "nav.sos": "অথুবা",
    "header.ops": "ফিল্ড অপস",
    "header.live": "লাইভ",
    "header.off": "অফ",
    "home.designated_corridor": "খনগৎলবা লম্বী করিডোর",
    "home.no_route": "লম্বী তৌদে",
    "home.clearance": "লম্বী শেংবা",
    "home.distance": "লাপ্না লৈবা",
    "home.outbox": "আউটবক্স",
    "home.sector_pass_rate": "চৎপগী রেট",
    "home.direct_route": "অচুম্বা লম্বী",
    "home.buffered_updates": "থম্লবা পাউদম",
    "home.synchronized": "পুন্সিনখ্রে",
    "home.queued": "ৱারোইশিনদে",
    "home.engage_navigation": "লম্বী য়েংবা হৌরো",
    "home.live_speed": "য়াংবা",
    "home.altitude": "ৱাংবা",
    "home.gnss_stream": "উপগ্রহ সংকেত",
    "home.transit_estimate": "মতৌ মতম",
    "home.hazards": "খুদোংথিবা",
    "home.noted": "উরে",
    "home.field_feed": "ক্ষেত্ৰগী পাউ",
    "home.view_all": "ময়াম য়েংউ",
    "home.no_hazards": "খুদোংথিবা লৈতে",
    "home.synced": "পুন্সিনখ্রে",
    "route.planner_title": "করিডোর প্ল্যানার",
    "route.planner_sub": "অফলাইন লম্বী য়েংনবা",
    "route.search_placeholder": "ডিপো নত্রগা লম্বী থীউ",
    "route.full_map": "মপুং ফাবা মানচিত্র",
    "route.exit_full": "থোকউ",
    "route.verified_hubs": "কৌশলগত কেন্দ্রশিং",
    "route.recenter_gps": "জিপিএস নৌনা থম্মু",
    "route.fit_route": "লম্বী য়েংউ",
    "route.engage_nav": "চৎপা হৌরো",
    "route.calculating": "লম্বী থীবগী মতম...",
    "route.route_ready": "লম্বী শেমরে",
    "route.live_results": "ফংলবা মফমশিং",
    "report.title": "খুদোংথিবা পাউদম",
    "report.subtitle": "হৌজিক্কী পাউ",
    "report.active_reporter": "পাউদম্লকপা মী",
    "report.fetch_gps": "লাইভ জিপিএস লৌউ",
    "report.locating_gps": "জিপিএস থীরি...",
    "report.gps_locked": "জিপিএস ফংলে",
    "report.simulated_gps": "সিমুলেশন জিপিএস",
    "report.category": "মখল",
    "report.severity": "অশুক্কী মাত্ৰা",
    "report.segment": "লম্বী খণ্ড",
    "report.report_title": "পাউদমগী মিং",
    "report.observations": "উখিবা ফীভম",
    "report.broadcast": "তাৎক্ষণিক ওইনা থারকউ",
    "report.offline_save": "অফলাইন থম্মু",
    "report.form_tab": "অনৌবা পাউদম",
    "report.history_tab": "পাউদমশিং",
    "sos.title": "অথুবা খুদোংথিবা সংকেত",
    "sos.subtitle": "অথুবা ব্রডকাস্ট",
    "sos.operator": "সংকেত থারকপা",
    "sos.hold_prompt": "সেকেন্দ ২ পাইদুনা থম্মু",
    "sos.active_status": "সংকেত থাররি",
    "sos.cancel_beacon": "সংকেত তোকউ",
    "sos.medical": "হিদাক লাংথক",
    "sos.breakdown": "গাড়ী থাদোকপা",
    "sos.threat": "লম্বী বাধা",
    "sync.title": "অফলাইন সিঙ্ক কেন্দ্র",
    "sync.subtitle": "টেলিমেট্রি সিঙ্ক",
    "sync.sync_now": "হৌজিক সিঙ্ক তৌউ",
    "sync.all_synced": "পুম্নমক সিঙ্ক ওইরে",
    "sync.pending_records": "রেকোৰ্ড য়াওরি",
    "sos.beacon_live": "জরুরী ত্রান্সপোন্দর লাইভ",
    "sos.broadcasting_telemetry": "জরুরী তেলিমেত্রী ত্রান্সমিৎ তৌরি",
    "sos.transmitting_desk": "ওপরেসন্স দেস্ক্তা কোওর্দিনেৎস থাদোকই",
    "sos.beacon_id": "বিকন আইদি",
    "sos.assigned_unit": "এসাইন্দ য়ুনিত",
    "sos.sector_role": "সেক্তর / থৌদাং",
    "sos.coordinates": "কোওর্দিনেৎস",
    "sos.accuracy_radius": "শুংনা য়ানবা রেদিয়স",
    "sos.packet_tx": "পাকেত ত্রান্সমিসন",
    "sos.safety_protocol": "সেফতি প্রোতোকোল · লিঙ্ক",
    "sos.standby": "তেনবাই",
    "sos.protocol_desc": "লম্বীগী খুদোংথীবা, গারী থৌবা য়াদবা নত্রগা অনাবা তারবদি ইমর্জেন্সী বিকন চলাইয়ু।",
    "sos.conditions_title": "খুদোংথীবগী ফিভম (অপসনেল)",
    "sos.hold_warning": "অশোইবদা অন তৌদনবা সেকেন্দ ২ নম্বদুনা থম্মু",
    "sync.radio_mode": "রেদিও ত্রান্সসিভর মোদ",
    "sync.uplink_controller": "তেলিমেত্রী অপলিঙ্ক কন্ত্রোলর",
    "sync.auto_adaptive": "ওতো (অদাপ্তিব)",
    "sync.manual_override": "মেনুএল ওভররাইদ",
    "sync.rtk_uplink": "লাইভ আর.তি.কে অপলিঙ্ক",
    "sync.mesh_network": "মেস নেত্বর্ক",
    "sync.airgap_protocol": "অফলাইন প্রটোকোল",
    "sync.outbox_pipeline": "আউতবোক্স পাইপলাইন",
    "sync.reports_queued": "রিপোর্ত লাইনদা লৈরি",
    "sync.outbox_cleared": "আউতবোক্স হাংলে",
    "sync.last_synced": "অরোইবা সিঙ্ক তৌখিবা",
    "sync.local_cache": "লোকেল ইন্দেক্সদিবি কেশ",
    "sync.map_sectors": "মেপ সেক্তর",
    "sync.reports": "রিপোর্তশিং",
    "sync.breadcrumbs": "লম্বীগী চিন",
    "sync.outbox_buffer": "আউতবোক্স বাফর",
    "sync.total_entries": "পুন্না এন্ত্রীশিং",
    "sync.empty_outbox": "আউতবোক্স হাংলে"
  },
  "lus": {
    "nav.home": "In",
    "nav.map": "Ram lem",
    "nav.report": "Ripawt",
    "nav.sync": "Zawmna",
    "nav.sos": "SOS",
    "header.ops": "Hnathawh",
    "header.live": "Nung",
    "header.off": "Chhia",
    "home.designated_corridor": "Kawng Ruahman Bika",
    "home.no_route": "Kawng ruahman a awm lo",
    "home.clearance": "Fihlimna",
    "home.distance": "Hlat zawng",
    "home.outbox": "Dah khawl",
    "home.sector_pass_rate": "Kal tlang theih zat",
    "home.direct_route": "Kawng tlang",
    "home.buffered_updates": "Thil thar khawl",
    "home.synchronized": "Thlunzawm tawh",
    "home.queued": "La nghak",
    "home.engage_navigation": "Kawng zawh tan rawh",
    "home.live_speed": "Chak zawng",
    "home.altitude": "Sanna",
    "home.gnss_stream": "GNSS Telemetry",
    "home.transit_estimate": "Hun chhung tur",
    "home.hazards": "Hlauhawmte",
    "home.noted": "hriat tawh",
    "home.field_feed": "Hmun hma chanchin",
    "home.view_all": "En vek rawh",
    "home.no_hazards": "Hlauhawm a awm lo",
    "home.synced": "Thlunzawm",
    "route.planner_title": "Kawng Ruahmanna",
    "route.planner_sub": "Offline Navigation leh Ram lem",
    "route.search_placeholder": "Kawng, Depot, emaw Pass zawng rawh",
    "route.full_map": "Ram lem pum",
    "route.exit_full": "Chhuak rawh",
    "route.verified_hubs": "Khuathlan Hmun Pawimawhte",
    "route.recenter_gps": "GPS awmna lai",
    "route.fit_route": "Kawng pum en rawh",
    "route.engage_nav": "Kalthiam tan rawh",
    "route.calculating": "Kawng chhut mek a ni...",
    "route.route_ready": "Kawng peih a ni tawh",
    "route.live_results": "Hmun hmuhte",
    "report.title": "Hmun Chanchin Thehdarh",
    "report.subtitle": "Hlauhawm thlen thar",
    "report.active_reporter": "Hriattirtu Mawhphurtu",
    "report.fetch_gps": "Taksa GPS hmun la rawh",
    "report.locating_gps": "Satellite GPS zawn mek...",
    "report.gps_locked": "GPS hmuh a ni tawh",
    "report.simulated_gps": "Lemchan GPS hmang mek",
    "report.category": "Hlauhawm Chi",
    "report.severity": "A nat zawng",
    "report.segment": "Kawng Hmun",
    "report.report_title": "Thupui",
    "report.observations": "Hmuh dan leh Dinhmun",
    "report.broadcast": "Thehdarh nghal rawh",
    "report.offline_save": "Offline-ah dah ṭha rawh",
    "report.form_tab": "Thehdarh Thar",
    "report.history_tab": "Hriattirna Hmasate",
    "sos.title": "Chhiatrupna Chhanhimna",
    "sos.subtitle": "Hmanhmawh Thawnchhuahna",
    "sos.operator": "Chhanhimtu",
    "sos.hold_prompt": "Sec 2 hmet reng rawh",
    "sos.active_status": "SOS THAWNCHHUAH MEK A NI",
    "sos.cancel_beacon": "Titawp rawh (Thil dik lo)",
    "sos.medical": "Damdawi Mamawh",
    "sos.breakdown": "Motor Chhia",
    "sos.threat": "Kawng Daltu / Hlauhawm",
    "sync.title": "Offline Thlunzawmna",
    "sync.subtitle": "Thil dah khawl thawn letna",
    "sync.sync_now": "Thlunzawm nghal vek rawh",
    "sync.all_synced": "Base nen a inzawm vek tawh",
    "sync.pending_records": "khawl a la awm",
    "sos.beacon_live": "Chhiatrupna Thawnna A Nung",
    "sos.broadcasting_telemetry": "Chhiatrupna Telemetry Thawn Mek",
    "sos.transmitting_desk": "Operations Desk hnenah satellite coordinates thawn mek a ni",
    "sos.beacon_id": "Beacon ID",
    "sos.assigned_unit": "Unit Ruat",
    "sos.sector_role": "Veng / Nihna",
    "sos.coordinates": "Coordinates",
    "sos.accuracy_radius": "Duhthusam Hlat zawng",
    "sos.packet_tx": "Thawn chhuah tawh zat",
    "sos.safety_protocol": "Himna Dan · Emergency Link",
    "sos.standby": "INPEIHSA",
    "sos.protocol_desc": "Kawng laka chhiatna tawk palh, lirthei chhia, emaw damlohna thut ah emergency transponder hi hmet rawh.",
    "sos.conditions_title": "Chhiatrupna Dinhmun (Duhthlan theih)",
    "sos.hold_warning": "Tihpalh lakah him nan second 2 hmeh vung vung a ngai",
    "sync.radio_mode": "Radio Inbiakpawhna Mode",
    "sync.uplink_controller": "Telemetry Uplink Enkawltu",
    "sync.auto_adaptive": "Mahni a inthlak thei",
    "sync.manual_override": "Mahni duha thlak",
    "sync.rtk_uplink": "Live RTK Uplink",
    "sync.mesh_network": "Mesh Network",
    "sync.airgap_protocol": "Airgap Dan",
    "sync.outbox_pipeline": "Outbox Pipeline",
    "sync.reports_queued": "Reports Inlar",
    "sync.outbox_cleared": "Outbox a ruak",
    "sync.last_synced": "Sync hnuhnung ber",
    "sync.local_cache": "Phone chhunga dahṭhat",
    "sync.map_sectors": "Map Vengte",
    "sync.reports": "Thu dawnte",
    "sync.breadcrumbs": "Hniak hnuhma",
    "sync.outbox_buffer": "Outbox Buffer",
    "sync.total_entries": "a vaia zat",
    "sync.empty_outbox": "Outbox a ruak"
  },
  "kha": {
    "nav.home": "Shnong",
    "nav.map": "Map",
    "nav.report": "Pyntip",
    "nav.sync": "Pyniasoh",
    "nav.sos": "SOS",
    "header.ops": "Ki Kam Nongtrei",
    "header.live": "Im",
    "header.off": "Lip",
    "home.designated_corridor": "Ka Lynti Ba La Bthah",
    "home.no_route": "Ym pat don lynti",
    "home.clearance": "Jinglait",
    "home.distance": "Jingjngai",
    "home.outbox": "Outbox",
    "home.sector_pass_rate": "Ka jinglait lynti",
    "home.direct_route": "Lynti beit",
    "home.buffered_updates": "Ki jingpyntip ba kynshew",
    "home.synchronized": "Pyniasoh lut",
    "home.queued": "Dang ap",
    "home.engage_navigation": "Sdang ia ka lynti",
    "home.live_speed": "Jingstet",
    "home.altitude": "Jingjrong",
    "home.gnss_stream": "GNSS Stream",
    "home.transit_estimate": "Por ba antad",
    "home.hazards": "Ki Jingma",
    "home.noted": "la tip",
    "home.field_feed": "Ki Khubor Nongtrei",
    "home.view_all": "Peit lut",
    "home.no_hazards": "Ym don jingma hangne",
    "home.synced": "Pyniasoh",
    "route.planner_title": "U Nongruah Lynti",
    "route.planner_sub": "Offline Navigation bad ki Tactical Map",
    "route.search_placeholder": "Wad ia ka Lynti, Depot lane Pass",
    "route.full_map": "Map baroh",
    "route.exit_full": "Mih noh",
    "route.verified_hubs": "Ki Kynhun ba donkam",
    "route.recenter_gps": "Pynbeit GPS",
    "route.fit_route": "Peit baroh ka lynti",
    "route.engage_nav": "Sdang ka leit ka wan",
    "route.calculating": "Dang khein ia ka lynti...",
    "route.route_ready": "La biang ka lynti",
    "route.live_results": "Ki jaka ba lap",
    "report.title": "Ka Ripot Jingjia",
    "report.subtitle": "Ki khubor jingma mar syn jia",
    "report.active_reporter": "U Nongpyntip",
    "report.fetch_gps": "Shim ia ka GPS live",
    "report.locating_gps": "Dang wad satellite GPS...",
    "report.gps_locked": "GPS la skhem",
    "report.simulated_gps": "GPS ba shu thaw",
    "report.category": "Jait jingjia",
    "report.severity": "Jingjur",
    "report.segment": "Ka bynta jong ka surok",
    "report.report_title": "Kyrteng ka ripot",
    "report.observations": "Kine ki jingtip",
    "report.broadcast": "Phah mar-ia-dep",
    "report.offline_save": "Kynshew ha outbox",
    "report.form_tab": "Ripot Bathymmai",
    "report.history_tab": "Ki Ripot Barim",
    "sos.title": "Ka Pyrta Jingiarap SOS",
    "sos.subtitle": "Jingpyntip ba Kyrkieh",
    "sos.operator": "Nongpyntip Kyrkieh",
    "sos.hold_prompt": "Khem 2 sekhon ban phah",
    "sos.active_status": "DANG PHAH IA KA SOS",
    "sos.cancel_beacon": "Pynsangeh (Ba Bakla)",
    "sos.medical": "Dawai / Doktor",
    "sos.breakdown": "Kali ba sniew",
    "sos.threat": "Jingma ha surok",
    "sync.title": "Ka jaka pyniasoh offline",
    "sync.subtitle": "Store-and-Forward Telemetry",
    "sync.sync_now": "Pyniasoh baroh mynta",
    "sync.all_synced": "La pyniasoh lut bad ka base",
    "sync.pending_records": "ki record dang don",
    "sos.beacon_live": "Ka Jingpyntip Jingeh Ka Khih",
    "sos.broadcasting_telemetry": "Pynphriang Telemetry Jingeh",
    "sos.transmitting_desk": "Phah Coordinates sha Operations Desk",
    "sos.beacon_id": "Beacon ID",
    "sos.assigned_unit": "Unit Ba la ai",
    "sos.sector_role": "Sector / Kam",
    "sos.coordinates": "Coordinates",
    "sos.accuracy_radius": "Jingjngai Ba Thikna",
    "sos.packet_tx": "Packet Ba la Phah",
    "sos.safety_protocol": "Ka Ai Jingiada · Emergency",
    "sos.standby": "AP KTI",
    "sos.protocol_desc": "Lada don jingeh ha surok, ka kali ka sniew lane don ba pang, pynkhih ia u transponder.",
    "sos.conditions_title": "Jinglong ka Jingeh (lah ban jied)",
    "sos.hold_warning": "Khem 2 sekhon ban lait na kaba pynkhih bakla",
    "sync.radio_mode": "Radio Transceiver Mode",
    "sync.uplink_controller": "Telemetry Uplink Controller",
    "sync.auto_adaptive": "Auto (Adaptive)",
    "sync.manual_override": "Da ka kti",
    "sync.rtk_uplink": "Live RTK Uplink",
    "sync.mesh_network": "Mesh Network",
    "sync.airgap_protocol": "Airgap Protocol",
    "sync.outbox_pipeline": "Outbox Pipeline",
    "sync.reports_queued": "Reports ba don ha line",
    "sync.outbox_cleared": "Outbox la sngewbha",
    "sync.last_synced": "Sync ba khadduh",
    "sync.local_cache": "Ka Storage jong ka Phone",
    "sync.map_sectors": "Ki Bynta jong ka Map",
    "sync.reports": "Ki Report",
    "sync.breadcrumbs": "Ki Dak Surok",
    "sync.outbox_buffer": "Outbox Buffer",
    "sync.total_entries": "baroh ki jingthoh",
    "sync.empty_outbox": "Outbox la sngewbha"
  },
  "grt": {
    "nav.home": "Nok",
    "nav.map": "Map",
    "nav.report": "Kobor",
    "nav.sync": "Nangdimat",
    "nav.sos": "SOS",
    "header.ops": "Kamani",
    "header.live": "Teng",
    "header.off": "Dondik",
    "home.designated_corridor": "Donbagimin Rama",
    "home.no_route": "Ramako donja",
    "home.clearance": "Rama Rongtalani",
    "home.distance": "Chel·ani",
    "home.outbox": "Outbox",
    "home.sector_pass_rate": "Re·ani rate",
    "home.direct_route": "Sronggimin rama",
    "home.buffered_updates": "Donkamingin kobor",
    "home.synchronized": "Nangdimatgimin",
    "home.queued": "Senggipa",
    "home.engage_navigation": "Re·ani Ramako A·bachenggbo",
    "home.live_speed": "Re·stretani",
    "home.altitude": "Chugimina",
    "home.gnss_stream": "GNSS stream",
    "home.transit_estimate": "Sokani somoi",
    "home.hazards": "Kenanirang",
    "home.noted": "ma·sigimin",
    "home.field_feed": "A·dokni kobor",
    "home.view_all": "Pilakko nibo",
    "home.no_hazards": "Kenani dongja",
    "home.synced": "Nangdimatgimin",
    "route.planner_title": "Ramani Plan",
    "route.planner_sub": "Offline Navigation aro Map",
    "route.search_placeholder": "Rama, Depot ba Pass-ko ambo",
    "route.full_map": "Gimik Map",
    "route.exit_full": "Ong·katbo",
    "route.verified_hubs": "Korang Hubs",
    "route.recenter_gps": "GPS Janggilbo",
    "route.fit_route": "Ramako matchot nibo",
    "route.engage_nav": "Ramako A·bachenggbo",
    "route.calculating": "Ramako hisap ka·enga...",
    "route.route_ready": "Rama tarigimin ong·aha",
    "route.live_results": "Nikgimin A·dok",
    "report.title": "A·dokni Kobor Report",
    "report.subtitle": "Kenani kobor",
    "report.active_reporter": "Watatgipa",
    "report.fetch_gps": "GPS A·dokko Ra·bo",
    "report.locating_gps": "GPS-ko sandienga...",
    "report.gps_locked": "GPS Man·aha",
    "report.simulated_gps": "Togimin GPS",
    "report.category": "Kenani Dingtang",
    "report.severity": "Kenani bil",
    "report.segment": "Ramani Bak",
    "report.report_title": "Koborni Buring",
    "report.observations": "Nikani kobor",
    "report.broadcast": "Ta·rake watatbo",
    "report.offline_save": "Outbox-o rakkibo",
    "report.form_tab": "Gital Report",
    "report.history_tab": "Gitcham Kobor",
    "sos.title": "Kenani SOS Transponder",
    "sos.subtitle": "Ta·rake watatani",
    "sos.operator": "SOS Watatgipa",
    "sos.hold_prompt": "Sec 2 sin·e rakkibo",
    "sos.active_status": "SOS-KO WATATENGA",
    "sos.cancel_beacon": "Dondikbo (Gualani)",
    "sos.medical": "Sam Bil",
    "sos.breakdown": "Gari Be·ani",
    "sos.threat": "Rama Champengani",
    "sync.title": "Offline Nangdimatani",
    "sync.subtitle": "Store-and-Forward Telemetry",
    "sync.sync_now": "Da·alo nangdimatbo",
    "sync.all_synced": "Base baksa nangdimataha",
    "sync.pending_records": "dongkua",
    "sos.beacon_live": "Distress Transponder Song.a",
    "sos.broadcasting_telemetry": "Emergency Telemetry Watataonga",
    "sos.transmitting_desk": "Operations Deskona Coordinates watataonga",
    "sos.beacon_id": "Beacon ID",
    "sos.assigned_unit": "On.gimin Unit",
    "sos.sector_role": "Sector / Kam",
    "sos.coordinates": "Coordinates",
    "sos.accuracy_radius": "Accuracy Radius",
    "sos.packet_tx": "Packet watataonga",
    "sos.safety_protocol": "Safety Protocol · Emergency",
    "sos.standby": "SENGBENGONGA",
    "sos.protocol_desc": "Ramao neng.nikaniko, gari nosto on.aniko, maiba sa.aniko ningo emergency transponderko jakkalbo.",
    "sos.conditions_title": "Neng.nikani Awastha (Optional)",
    "sos.hold_warning": "Komae switch on gnani champengna second 2 sintebo",
    "sync.radio_mode": "Radio Transceiver Mode",
    "sync.uplink_controller": "Telemetry Uplink Controller",
    "sync.auto_adaptive": "Auto (Adaptive)",
    "sync.manual_override": "Jakkalani nambatgipa",
    "sync.rtk_uplink": "Live RTK Uplink",
    "sync.mesh_network": "Mesh Network",
    "sync.airgap_protocol": "Airgap Protocol",
    "sync.outbox_pipeline": "Outbox Pipeline",
    "sync.reports_queued": "Reports tari onganiko",
    "sync.outbox_cleared": "Outbox bang.ja",
    "sync.last_synced": "Sync Matchotgipa",
    "sync.local_cache": "Jikani IndexedDB Cache",
    "sync.map_sectors": "Map Sectors",
    "sync.reports": "Reports",
    "sync.breadcrumbs": "Rama Chin",
    "sync.outbox_buffer": "Outbox Buffer",
    "sync.total_entries": "gimik entries",
    "sync.empty_outbox": "Outbox bang.ja"
  },
  "brx": {
    "nav.home": "नखर",
    "nav.map": "मानचित्र",
    "nav.report": "खौरां",
    "nav.sync": "फोनांजाब",
    "nav.sos": "आपत",
    "header.ops": "फिल्ड खामानि",
    "header.live": "लायभ",
    "header.off": "अफ",
    "home.designated_corridor": "थि खालामनाय लामा",
    "home.no_route": "लामा गैया",
    "home.clearance": "उदां",
    "home.distance": "गोजान",
    "home.outbox": "आउटबक्स",
    "home.sector_pass_rate": "बारग'नायनि दर",
    "home.direct_route": "थोंजों लामा",
    "home.buffered_updates": "दंथुमनाय खौरां",
    "home.synchronized": "फोनांजाबबाय",
    "home.queued": "नेबाय थानाय",
    "home.engage_navigation": "लामा नायनो जागाय",
    "home.live_speed": "खारनाय",
    "home.altitude": "गोजौथि",
    "home.gnss_stream": "जि.एन.एस.एस. स्ट्रिम",
    "home.transit_estimate": "साननाय सम",
    "home.hazards": "खैफोद",
    "home.noted": "नोंखाय",
    "home.field_feed": "फिल्डनि खौरां",
    "home.view_all": "गासैखौबो नाय",
    "home.no_hazards": "खैफोद गैया",
    "home.synced": "फोनांजाबबाय",
    "route.planner_title": "लामा थांखिनाय",
    "route.planner_sub": "अफलाइन नेभिगेसन आरो म्याप",
    "route.search_placeholder": "डिपो एबा लामा नागिर",
    "route.full_map": "गासै म्याप",
    "route.exit_full": "ओंखार",
    "route.verified_hubs": "मख'जाथाव मिरुफोर",
    "route.recenter_gps": "जिपिएस गेजेर",
    "route.fit_route": "गासै लामा नाय",
    "route.engage_nav": "लामा जागाय",
    "route.calculating": "लामा सानगासिनो...",
    "route.route_ready": "लामा थियारि जाबाय",
    "route.live_results": "मोननाय जायगा",
    "report.title": "जाथायनि खौरां",
    "report.subtitle": "थाब खैफोद खौरां",
    "report.active_reporter": "खौरां दैथायग्रा",
    "report.fetch_gps": "जिपिएस ला",
    "report.locating_gps": "जिपिएस नागिरगासिनो...",
    "report.gps_locked": "जिपिएस मोनबाय",
    "report.simulated_gps": "बनाव जिपिएस",
    "report.category": "खौरांनि रोखोम",
    "report.severity": "गोख्रोंथि",
    "report.segment": "लामानि बाहागो",
    "report.report_title": "खौरांनि मुं",
    "report.observations": "नुनाय जाथाय",
    "report.broadcast": "थाब दैथायहर",
    "report.offline_save": "अफलाइन दोन",
    "report.form_tab": "गोदान खौरां",
    "report.history_tab": "मुलुग खौरां",
    "sos.title": "आपतकालीन खौरां (SOS)",
    "sos.subtitle": "गोख्रों मदद खौरां",
    "sos.operator": "दैथायग्रा",
    "sos.hold_prompt": "२ सेकेन्ड दबथायना दोन",
    "sos.active_status": "SOS दैथायगासिनो दं",
    "sos.cancel_beacon": "गार (नोंखाय अलार्म)",
    "sos.medical": "फाहामथाय",
    "sos.breakdown": "गारि गाज्रि जानाय",
    "sos.threat": "लामा हेंथा",
    "sync.title": "अफलाइन फोनांजाब मिरु",
    "sync.subtitle": "Store-and-Forward",
    "sync.sync_now": "गासैबो दा फोनांजाब",
    "sync.all_synced": "गासैबो फोनांजाबबाय",
    "sync.pending_records": "दंथुमनाय दं",
    "sos.beacon_live": "जिउ बासायग्रा ट्रान्सपोण्डार गोथां",
    "sos.broadcasting_telemetry": "जिउ बासायग्रा टेलिमेट्रि फोसावबाय थादों",
    "sos.transmitting_desk": "अपेरेसन डेक्सआव जेरैवबो सेटेलाइट कोर्डिनेट दैथायहरदों",
    "sos.beacon_id": "बिकन आइदि",
    "sos.assigned_unit": "थिसननाय इउनिथ",
    "sos.sector_role": "बायजो / खामानि",
    "sos.coordinates": "कोर्डिनेट",
    "sos.accuracy_radius": "गेबें दायरा",
    "sos.packet_tx": "पेकेत दैथायनाय",
    "sos.safety_protocol": "रैखा प्रोटोकल · जिउ बासायग्रा",
    "sos.standby": "नेबाय थानाय",
    "sos.protocol_desc": "लामा आव खैफोद जायोबा एबा गारि गाज्रि जायोबा जिउ बासायग्रा संखो बाहाय।",
    "sos.conditions_title": "खैफोदनि थासारि (गोसो बादि)",
    "sos.hold_warning": "गोरोन्थियै जागायनायखौ होबथानो सेकेन्द 2 थुना दोन",
    "sync.radio_mode": "रेडिअ' ट्रान्ससिभार म'ड",
    "sync.uplink_controller": "टेलिमेट्रि आपलिंक कन्त्रोलार",
    "sync.auto_adaptive": "गावनो गाव (अदাপ্তिब)",
    "sync.manual_override": "आथिं-आखायाव",
    "sync.rtk_uplink": "लाइभ आरथिके आपलिंक",
    "sync.mesh_network": "मेश नेथवर्क",
    "sync.airgap_protocol": "एयारगेप प्रोटोकल",
    "sync.outbox_pipeline": "आउटबक्स पाइपलाइन",
    "sync.reports_queued": "खौरां कतारआव दं",
    "sync.outbox_cleared": "आउटबक्स लांदां",
    "sync.last_synced": "जोबथा सिंक",
    "sync.local_cache": "लोकेल IndexedDB केस",
    "sync.map_sectors": "मानचित्र बाहागोफोर",
    "sync.reports": "खौरांफोर",
    "sync.breadcrumbs": "लामा दावबायनाय",
    "sync.outbox_buffer": "आउटबक्स बाफार",
    "sync.total_entries": "गासै हाबनायफोर",
    "sync.empty_outbox": "आउटबक्स लांदां"
  },
  "trp": {
    "nav.home": "Nok",
    "nav.map": "Map",
    "nav.report": "Koktuma",
    "nav.sync": "Khoboi",
    "nav.sos": "SOS",
    "header.ops": "Kamani",
    "header.live": "Live",
    "header.off": "Off",
    "home.designated_corridor": "Rwchapna Lama",
    "home.no_route": "Lama krwng ya",
    "home.clearance": "Lama Kaham",
    "home.distance": "Hallok",
    "home.outbox": "Outbox",
    "home.sector_pass_rate": "Thangna rate",
    "home.direct_route": "Chuba lama",
    "home.buffered_updates": "Thwngba koktuma",
    "home.synchronized": "Khoboi paiha",
    "home.queued": "Nalaiman tongo",
    "home.engage_navigation": "Lama naina chengo",
    "home.live_speed": "Phunukmani",
    "home.altitude": "Chukhani",
    "home.gnss_stream": "GNSS stream",
    "home.transit_estimate": "Swnamani jora",
    "home.hazards": "Kotor Lama",
    "home.noted": "Siha",
    "home.field_feed": "Aaphani kok",
    "home.view_all": "Jotoni nai",
    "home.no_hazards": "Jorani kotor khorok ya",
    "home.synced": "Khoboi paiha",
    "route.planner_title": "Lama Chwngmani",
    "route.planner_sub": "Offline Navigation bai Map",
    "route.search_placeholder": "Lama, Depot bai Pass naidi",
    "route.full_map": "Joto Map",
    "route.exit_full": "Hokor di",
    "route.verified_hubs": "Belai Nangmani Hubs",
    "route.recenter_gps": "GPS Kwtal khlai",
    "route.fit_route": "Lama naidi",
    "route.engage_nav": "Lama chengdi",
    "route.calculating": "Lama hisap tongo...",
    "route.route_ready": "Lama siapaiha",
    "route.live_results": "Manmwi nokhor",
    "report.title": "Aaphani Koktuma",
    "report.subtitle": "Kotor jora koktuma",
    "report.active_reporter": "Koktuma rwgwi",
    "report.fetch_gps": "GPS Rwbai",
    "report.locating_gps": "GPS naising tongo...",
    "report.gps_locked": "GPS Mano",
    "report.simulated_gps": "Simulated GPS",
    "report.category": "Koktuma dophani",
    "report.severity": "Chukani",
    "report.segment": "Lamani bwtwk",
    "report.report_title": "Koktuma mung",
    "report.observations": "Naimani",
    "report.broadcast": "Kharoksa phohor",
    "report.offline_save": "Outbox-o toni",
    "report.form_tab": "Kwtal Koktuma",
    "report.history_tab": "Kwtwi Koktuma",
    "sos.title": "Tongkhor SOS",
    "sos.subtitle": "Jora khatwng phohormani",
    "sos.operator": "SOS Rwgwi",
    "sos.hold_prompt": "Sec 2 rimdi phohorna",
    "sos.active_status": "SOS PHOHOR TONGO",
    "sos.cancel_beacon": "Khori ridi (Gualmani)",
    "sos.medical": "Daktarni",
    "sos.breakdown": "Gari bemani",
    "sos.threat": "Lamani Kotor",
    "sync.title": "Offline Khoboi Hub",
    "sync.subtitle": "Store-and-Forward Telemetry",
    "sync.sync_now": "Dapalo khoboi di",
    "sync.all_synced": "Joto base bai khoboi paiha",
    "sync.pending_records": "tongo",
    "sos.beacon_live": "Kotor Lama Beakon Salai",
    "sos.broadcasting_telemetry": "Emergency Telemetry Khorokba",
    "sos.transmitting_desk": "Operations Desk-o satellite coordinates thari",
    "sos.beacon_id": "Beacon ID",
    "sos.assigned_unit": "Unit Khwlai",
    "sos.sector_role": "Sector / Role",
    "sos.coordinates": "Coordinates",
    "sos.accuracy_radius": "Radius Thik",
    "sos.packet_tx": "Packet Phah",
    "sos.safety_protocol": "Safety Protocol",
    "sos.standby": "STANDBY",
    "sos.protocol_desc": "Lama khotor ongkhe eba gari phatle emergency beakon khwlai di.",
    "sos.conditions_title": "Distress Conditions (Optional)",
    "sos.hold_warning": "Galti ongma tangna 2 second thikhe rim di",
    "sync.radio_mode": "Radio Transceiver Mode",
    "sync.uplink_controller": "Telemetry Controller",
    "sync.auto_adaptive": "Auto Mode",
    "sync.manual_override": "Manual Mode",
    "sync.rtk_uplink": "Live Uplink",
    "sync.mesh_network": "Mesh Network",
    "sync.airgap_protocol": "Airgap Protocol",
    "sync.outbox_pipeline": "Outbox Pipeline",
    "sync.reports_queued": "Reports Thik",
    "sync.outbox_cleared": "Outbox Khali",
    "sync.last_synced": "Last Synced",
    "sync.local_cache": "Local Cache",
    "sync.map_sectors": "Map Sectors",
    "sync.reports": "Reports",
    "sync.breadcrumbs": "Lama Chin",
    "sync.outbox_buffer": "Outbox Buffer",
    "sync.total_entries": "Total Entries",
    "sync.empty_outbox": "Outbox Khali"
  },
  "nag": {
    "nav.home": "Ghar",
    "nav.map": "Naksha",
    "nav.report": "Khobor",
    "nav.sync": "Mila",
    "nav.sos": "Bipod",
    "header.ops": "Field Kaam",
    "header.live": "Live",
    "header.off": "Off",
    "home.designated_corridor": "Thik Kora Rasta",
    "home.no_route": "Kun rasta nai",
    "home.clearance": "Khula Rasta",
    "home.distance": "Distance",
    "home.outbox": "Jama Kora",
    "home.sector_pass_rate": "Pass kora rate",
    "home.direct_route": "Sidha rasta",
    "home.buffered_updates": "Jama khobor",
    "home.synchronized": "Mili jaishe",
    "home.queued": "Baki ase",
    "home.engage_navigation": "Rasta Jabo Shuru Kori",
    "home.live_speed": "Speed",
    "home.altitude": "Opor",
    "home.gnss_stream": "GNSS stream",
    "home.transit_estimate": "Time laga hisap",
    "home.hazards": "Bipod khan",
    "home.noted": "paise",
    "home.field_feed": "Field laga khobor",
    "home.view_all": "Sob sabo",
    "home.no_hazards": "Kun bipod nai",
    "home.synced": "Milise",
    "route.planner_title": "Rasta Banawa",
    "route.planner_sub": "Offline Navigation & Map",
    "route.search_placeholder": "Rasta, Depot ba Pass bisari",
    "route.full_map": "Pura Map",
    "route.exit_full": "Ulao",
    "route.verified_hubs": "Bhal Hubs khan",
    "route.recenter_gps": "GPS Maji te anibi",
    "route.fit_route": "Pura rasta sabo",
    "route.engage_nav": "Rasta jao",
    "route.calculating": "Rasta hisap kori ase...",
    "route.route_ready": "Rasta taiyar",
    "route.live_results": "Pawa jaga khan",
    "report.title": "Field Bipod Khobor",
    "report.subtitle": "Live bipod update",
    "report.active_reporter": "Reporter Manu",
    "report.fetch_gps": "GPS Lobi",
    "report.locating_gps": "GPS bisari ase...",
    "report.gps_locked": "GPS pai gole",
    "report.simulated_gps": "Nakli GPS",
    "report.category": "Khobor type",
    "report.severity": "Kiman dangor",
    "report.segment": "Rasta laga hissa",
    "report.report_title": "Khobor title",
    "report.observations": "Dekha kotha",
    "report.broadcast": "Khobor Pathai Dibi",
    "report.offline_save": "Outbox te rakh",
    "report.form_tab": "Notun Khobor",
    "report.history_tab": "Purana Khobor",
    "sos.title": "Bipod SOS Signal",
    "sos.subtitle": "Emergency Broadcast",
    "sos.operator": "SOS Manu",
    "sos.hold_prompt": "2 Second Dhori Rakhibi",
    "sos.active_status": "SOS SIGNAL JAI ASE",
    "sos.cancel_beacon": "Bondho Kori Dibi",
    "sos.medical": "Dawa / Hospital",
    "sos.breakdown": "Gari Khrap",
    "sos.threat": "Rasta Rukha",
    "sync.title": "Offline Mila Centre",
    "sync.subtitle": "Store-and-Forward",
    "sync.sync_now": "Sob mili dyo",
    "sync.all_synced": "Sob base logote milise",
    "sync.pending_records": "baki ase",
    "sos.beacon_live": "Emergency Signal Chalu Ase",
    "sos.broadcasting_telemetry": "Emergency Khabar Send Hoishe",
    "sos.transmitting_desk": "Main HQ te real-time GPS location jaishe",
    "sos.beacon_id": "Beacon ID",
    "sos.assigned_unit": "Assigned Gaari",
    "sos.sector_role": "Area / Kaam",
    "sos.coordinates": "GPS Location",
    "sos.accuracy_radius": "Exact Range",
    "sos.packet_tx": "Packet Signal Count",
    "sos.safety_protocol": "Safety Protocol · Emergency",
    "sos.standby": "TAYAR ASE",
    "sos.protocol_desc": "Raasta te bishi dukh paise, gaari kharap hoishe koile emergency beacon button dababi.",
    "sos.conditions_title": "Problem Type (Choose koribo pare)",
    "sos.hold_warning": "Galti se click nohobo karne 2 second dabai thakibi",
    "sync.radio_mode": "Radio Network Mode",
    "sync.uplink_controller": "Data Send Controller",
    "sync.auto_adaptive": "Auto Switch",
    "sync.manual_override": "Manual Chalu",
    "sync.rtk_uplink": "Live Fast Network",
    "sync.mesh_network": "Mesh / 2G Network",
    "sync.airgap_protocol": "Full Offline Mode",
    "sync.outbox_pipeline": "Outbox Line",
    "sync.reports_queued": "Reports Line Te Ase",
    "sync.outbox_cleared": "Outbox Khali Ase",
    "sync.last_synced": "Last Sync Hoishe",
    "sync.local_cache": "Phone Memory Cache",
    "sync.map_sectors": "Map Area",
    "sync.reports": "Reports",
    "sync.breadcrumbs": "Pisa Rasta",
    "sync.outbox_buffer": "Outbox Buffer",
    "sync.total_entries": "Total Entries",
    "sync.empty_outbox": "Outbox Khali Ase"
  },
  "ne": {
    "nav.home": "गृह",
    "nav.map": "नक्सा",
    "nav.report": "रिपोर्ट",
    "nav.sync": "सिङ्क",
    "nav.sos": "संकट",
    "header.ops": "फिल्ड कार्य",
    "header.live": "प्रत्यक्ष",
    "header.off": "अफलाइन",
    "home.designated_corridor": "तोकिएको ट्रान्जिट कोरिडोर",
    "home.no_route": "कुनै मार्ग तोकिएको छैन",
    "home.clearance": "क्लियरेन्स",
    "home.distance": "दूरी",
    "home.outbox": "आउटबक्स",
    "home.sector_pass_rate": "क्षेत्र पास दर",
    "home.direct_route": "प्रत्यक्ष मार्ग",
    "home.buffered_updates": "बफर गरिएका अपडेटहरू",
    "home.synchronized": "सिङ्क्रोनाइज्ड",
    "home.queued": "पर्खिरहेको",
    "home.engage_navigation": "नेभिगेसन सुरु गर्नुहोस्",
    "home.live_speed": "प्रत्यक्ष गति",
    "home.altitude": "उचाइ",
    "home.gnss_stream": "GNSS टेलिमेट्री",
    "home.transit_estimate": "अनुमानित समय",
    "home.hazards": "खतराहरू",
    "home.noted": "दर्ता भएको",
    "home.field_feed": "फिल्ड टेलिमेट्री फिड",
    "home.view_all": "सबै हेर्नुहोस्",
    "home.no_hazards": "कुनै खतरा छैन",
    "home.synced": "सिङ्क भयो",
    "route.planner_title": "ट्रान्जिट कोरिडोर योजनाकार",
    "route.planner_sub": "अफलाइन नेभिगेसन र नक्सा",
    "route.search_placeholder": "कोरिडोर, डिपो वा भञ्ज्याङ खोज्नुहोस्",
    "route.full_map": "पूर्ण नक्सा",
    "route.exit_full": "बाहिर निस्कनुहोस्",
    "route.verified_hubs": "प्रमाणित रणनीतिक केन्द्रहरू",
    "route.recenter_gps": "जीपीएस केन्द्रित",
    "route.fit_route": "सम्पूर्ण मार्ग हेर्नुहोस्",
    "route.engage_nav": "नेभिगेसन सुरु",
    "route.calculating": "मार्ग गणना हुँदैछ...",
    "route.route_ready": "मार्ग तयार भयो",
    "route.live_results": "फेला परेका स्थानहरू",
    "report.title": "फिल्ड घटना रिपोर्ट",
    "report.subtitle": "प्रत्यक्ष खतरा फिड",
    "report.active_reporter": "सक्रिय रिपोर्टर",
    "report.fetch_gps": "प्रत्यक्ष जीपीएस लिनुहोस्",
    "report.locating_gps": "उपग्रह जीपीएस खोज्दै...",
    "report.gps_locked": "जीपीएस लक भयो",
    "report.simulated_gps": "नक्कली जीपीएस सक्रिय",
    "report.category": "घटनाको प्रकार",
    "report.severity": "गम्भीरता",
    "report.segment": "सडक खण्ड",
    "report.report_title": "रिपोर्ट शीर्षक",
    "report.observations": "फिल्ड अवलोकन",
    "report.broadcast": "तुरुन्त रिपोर्ट पठाउनुहोस्",
    "report.offline_save": "अफलाइन बचत गर्नुहोस्",
    "report.form_tab": "नयाँ रिपोर्ट",
    "report.history_tab": "इतिहास",
    "sos.title": "आपतकालीन संकट संकेत",
    "sos.subtitle": "आपतकालीन प्रसारण",
    "sos.operator": "संकट अपरेटर",
    "sos.hold_prompt": "२ सेकेन्ड थिचिराख्नुहोस्",
    "sos.active_status": "संकट संकेत प्रसारण हुँदैछ",
    "sos.cancel_beacon": "संकेत रद्द गर्नुहोस्",
    "sos.medical": "उपचार प्राथमिकता",
    "sos.breakdown": "गाडी बिग्रिएको",
    "sos.threat": "सडक अवरोध / खतरा",
    "sync.title": "अफलाइन सिङ्क केन्द्र",
    "sync.subtitle": "स्टोर-एन्ड-फरवर्ड",
    "sync.sync_now": "अहिले नै सबै सिङ्क गर्नुहोस्",
    "sync.all_synced": "सबै रेकर्डहरू सिङ्क भए",
    "sync.pending_records": "रेकर्ड बाँकी छन्",
    "sos.beacon_live": "आपतकालीन ट्रान्सपोन्डर सक्रिय",
    "sos.broadcasting_telemetry": "आपतकालीन टेलिमेट्री प्रसारण भइरहेछ",
    "sos.transmitting_desk": "अपरेशन डेस्कमा उपग्रह निर्देशांक पठाइँदैछ",
    "sos.beacon_id": "बीकन आइडी",
    "sos.assigned_unit": "तोकिएको एकाई",
    "sos.sector_role": "क्षेत्र / भूमिका",
    "sos.coordinates": "निर्देशांक",
    "sos.accuracy_radius": "शुद्धता दायरा",
    "sos.packet_tx": "प्याकेट प्रसारण",
    "sos.safety_protocol": "सुरक्षा प्रोटोकल · आपतकालीन लिङ्क",
    "sos.standby": "तयार अवस्था",
    "sos.protocol_desc": "बाटोमा गम्भीर जोखिम, गाडी बिग्रिएमा वा स्वास्थ्य संकटमा आपतकालीन ट्रान्सपोन्डर चालु गर्नुहोस्।",
    "sos.conditions_title": "संकट स्थितिहरू (ऐच्छिक)",
    "sos.hold_warning": "भूलवश चालु हुनबाट रोक्न २ सेकेन्ड थिचिराख्नुहोस्",
    "sync.radio_mode": "रेडियो ट्रान्सिभर मोड",
    "sync.uplink_controller": "टेलिमेट्री अपलिङ्क नियन्त्रक",
    "sync.auto_adaptive": "स्वचालित (अनुकूली)",
    "sync.manual_override": "म्यानुअल नियन्त्रण",
    "sync.rtk_uplink": "प्रत्यक्ष RTK अपलिङ्क",
    "sync.mesh_network": "मेश नेटवर्क (ढिलो)",
    "sync.airgap_protocol": "एयरग्याप प्रोटोकल (अफलाइन)",
    "sync.outbox_pipeline": "आउटबक्स पाइपलाइन",
    "sync.reports_queued": "रिपोर्टहरू लामबद्ध",
    "sync.outbox_cleared": "आउटबक्स खाली छ",
    "sync.last_synced": "अन्तिम सिंक",
    "sync.local_cache": "स्थानीय IndexedDB क्यास",
    "sync.map_sectors": "नक्सा क्षेत्रहरू",
    "sync.reports": "प्रतिवेदनहरू",
    "sync.breadcrumbs": "यात्रा पथ",
    "sync.outbox_buffer": "आउटबक्स बफर",
    "sync.total_entries": "कुल प्रविष्टिहरू",
    "sync.empty_outbox": "आउटबक्स खाली छ"
  },
  "es": {
    "nav.home": "Inicio",
    "nav.map": "Mapa",
    "nav.report": "Reporte",
    "nav.sync": "Sinc",
    "nav.sos": "SOS",
    "header.ops": "Ops Campo",
    "header.live": "En vivo",
    "header.off": "Off",
    "home.designated_corridor": "Corredor de Tránsito Designado",
    "home.no_route": "Sin ruta asignada",
    "home.clearance": "Paso libre",
    "home.distance": "Distancia",
    "home.outbox": "Bandeja",
    "home.sector_pass_rate": "Tasa de paso del sector",
    "home.direct_route": "Ruta directa",
    "home.buffered_updates": "Actualizaciones en búfer",
    "home.synchronized": "Sincronizado",
    "home.queued": "en cola",
    "home.engage_navigation": "Iniciar Navegación del Corredor",
    "home.live_speed": "Velocidad",
    "home.altitude": "Altitud Barométrica",
    "home.gnss_stream": "Flujo GNSS",
    "home.transit_estimate": "Estimación de Tránsito",
    "home.hazards": "Peligros",
    "home.noted": "registrados",
    "home.field_feed": "Feed de Telemetría",
    "home.view_all": "Ver todo",
    "home.no_hazards": "No hay peligros reportados",
    "home.synced": "Sinc",
    "route.planner_title": "Planificador de Corredores",
    "route.planner_sub": "Rutas sin conexión y Mapas Tácticos",
    "route.search_placeholder": "Buscar Corredor, Depósito o Paso",
    "route.full_map": "Mapa Completo",
    "route.exit_full": "Salir",
    "route.verified_hubs": "Centros Estratégicos Verificados",
    "route.recenter_gps": "Recentrar GPS",
    "route.fit_route": "Ajustar Ruta",
    "route.engage_nav": "Iniciar Ruta",
    "route.calculating": "Calculando ruta...",
    "route.route_ready": "Ruta Lista",
    "route.live_results": "Ubicaciones encontradas",
    "report.title": "Reporte de Incidentes de Campo",
    "report.subtitle": "Feed de peligros en tiempo real",
    "report.active_reporter": "Reportero Activo",
    "report.fetch_gps": "Obtener GPS en Tiempo Real",
    "report.locating_gps": "Adquiriendo señal GPS satelital...",
    "report.gps_locked": "GPS Satelital Bloqueado",
    "report.simulated_gps": "GPS Simulado Activo",
    "report.category": "Categoría del Incidente",
    "report.severity": "Nivel de Severidad",
    "report.segment": "Segmento de Carretera / Corredor",
    "report.report_title": "Título del Reporte",
    "report.observations": "Observaciones de Campo",
    "report.broadcast": "Transmitir Reporte Ahora",
    "report.offline_save": "Guardar en Bandeja Offline",
    "report.form_tab": "Nuevo Reporte",
    "report.history_tab": "Historial",
    "sos.title": "Transpondedor de Emergencia",
    "sos.subtitle": "Transmisión de Emergencia Encriptada",
    "sos.operator": "Operador en Peligro",
    "sos.hold_prompt": "Mantén presionado 2 segundos para transmitir",
    "sos.active_status": "BALIZA DE SOS TRANSMITIENDO",
    "sos.cancel_beacon": "Cancelar Baliza (Falsa Alarma)",
    "sos.medical": "Prioridad Médica",
    "sos.breakdown": "Avería del Vehículo",
    "sos.threat": "Obstáculo en Ruta / Amenaza",
    "sync.title": "Centro de Sincronización Offline",
    "sync.subtitle": "Telemetría de Almacenamiento y Envío",
    "sync.sync_now": "Sincronizar Todo Ahora",
    "sync.all_synced": "Todos los registros sincronizados",
    "sync.pending_records": "registros en espera",
    "sos.beacon_live": "Transpondedor de Emergencia Activo",
    "sos.broadcasting_telemetry": "Transmitiendo Telemetría de Emergencia",
    "sos.transmitting_desk": "Coordenadas satelitales en tiempo real a la central de operaciones",
    "sos.beacon_id": "ID de Baliza",
    "sos.assigned_unit": "Unidad Asignada",
    "sos.sector_role": "Sector / Rol",
    "sos.coordinates": "Coordenadas",
    "sos.accuracy_radius": "Radio de Precisión",
    "sos.packet_tx": "Transmisiones de Paquetes",
    "sos.safety_protocol": "Protocolo de Seguridad · Enlace de Emergencia",
    "sos.standby": "EN ESPERA",
    "sos.protocol_desc": "En caso de peligro crítico, avería del vehículo o emergencia médica, active el transpondedor.",
    "sos.conditions_title": "Condiciones de Emergencia (Opcional)",
    "sos.hold_warning": "Mantenga presionado 2 segundos para evitar activaciones accidentales",
    "sync.radio_mode": "Modo de Transceptor de Radio",
    "sync.uplink_controller": "Controlador de Enlace de Telemetría",
    "sync.auto_adaptive": "Automático (Adaptativo)",
    "sync.manual_override": "Control Manual",
    "sync.rtk_uplink": "Enlace RTK en Vivo",
    "sync.mesh_network": "Red Mesh (Baja Velocidad)",
    "sync.airgap_protocol": "Protocolo Airgap (Sin Red)",
    "sync.outbox_pipeline": "Bandeja de Salida",
    "sync.reports_queued": "Informes en Cola",
    "sync.outbox_cleared": "Bandeja Limpia",
    "sync.last_synced": "Última sincronización",
    "sync.local_cache": "Caché Local IndexedDB",
    "sync.map_sectors": "Sectores de Mapa",
    "sync.reports": "Informes",
    "sync.breadcrumbs": "Rastro GPS",
    "sync.outbox_buffer": "Búfer de Salida",
    "sync.total_entries": "entradas totales",
    "sync.empty_outbox": "La bandeja de salida está vacía"
  },
  "fr": {
    "nav.home": "Accueil",
    "nav.map": "Carte",
    "nav.report": "Signaler",
    "nav.sync": "Synchro",
    "nav.sos": "SOS",
    "header.ops": "Opérations",
    "header.live": "Direct",
    "header.off": "Hors ligne",
    "home.designated_corridor": "Couloir de Transit Désigné",
    "home.no_route": "Aucun itinéraire assigné",
    "home.clearance": "Dégagement",
    "home.distance": "Distance",
    "home.outbox": "Boîte d'envoi",
    "home.sector_pass_rate": "Taux de passage secteur",
    "home.direct_route": "Itinéraire direct",
    "home.buffered_updates": "Mises à jour en mémoire",
    "home.synchronized": "Synchronisé",
    "home.queued": "en file d'attente",
    "home.engage_navigation": "Démarrer la Navigation",
    "home.live_speed": "Vitesse réelle",
    "home.altitude": "Altitude barométrique",
    "home.gnss_stream": "Flux GNSS",
    "home.transit_estimate": "Estimation du trajet",
    "home.hazards": "Dangers",
    "home.noted": "signalés",
    "home.field_feed": "Flux Télémétrique de Terrain",
    "home.view_all": "Voir tout",
    "home.no_hazards": "Aucun danger dans ce secteur",
    "home.synced": "Synchro",
    "route.planner_title": "Planificateur de Couloir",
    "route.planner_sub": "Routage hors-ligne et cartes tactiques",
    "route.search_placeholder": "Rechercher couloir, dépôt ou col",
    "route.full_map": "Plein Écran",
    "route.exit_full": "Quitter",
    "route.verified_hubs": "Pôles Logistiques Vérifiés",
    "route.recenter_gps": "Recentrer GPS",
    "route.fit_route": "Ajuster l'itinéraire",
    "route.engage_nav": "Démarrer Navigation",
    "route.calculating": "Calcul de l'itinéraire...",
    "route.route_ready": "Itinéraire Prêt",
    "route.live_results": "Lieux trouvés",
    "report.title": "Rapport d'Incident de Terrain",
    "report.subtitle": "Flux d'alertes en temps réel",
    "report.active_reporter": "Agent de Terrain Actif",
    "report.fetch_gps": "Obtenir la Position GPS en Direct",
    "report.locating_gps": "Recherche du signal GPS satellite...",
    "report.gps_locked": "Signal GPS Verrouillé",
    "report.simulated_gps": "GPS simulé actif",
    "report.category": "Catégorie de l'incident",
    "report.severity": "Gravité",
    "report.segment": "Tronçon routier",
    "report.report_title": "Titre du rapport",
    "report.observations": "Observations de terrain",
    "report.broadcast": "Diffuser le rapport immédiatement",
    "report.offline_save": "Enregistrer hors-ligne",
    "report.form_tab": "Nouveau Rapport",
    "report.history_tab": "Historique",
    "sos.title": "Balise de Détresse SOS",
    "sos.subtitle": "Diffusion d'urgence chiffrée prioritaire",
    "sos.operator": "Opérateur en détresse",
    "sos.hold_prompt": "Maintenez 2 secondes pour émettre",
    "sos.active_status": "BALISE DE DÉTRESSE EN COURS",
    "sos.cancel_beacon": "Annuler la balise (Fausse alerte)",
    "sos.medical": "Priorité Médicale",
    "sos.breakdown": "Panne Véhicule",
    "sos.threat": "Obstacle / Menace",
    "sync.title": "Centre de Synchronisation Hors-ligne",
    "sync.subtitle": "Télémétrie Store-and-Forward",
    "sync.sync_now": "Tout synchroniser maintenant",
    "sync.all_synced": "Tous les enregistrements synchronisés",
    "sync.pending_records": "enregistrements en attente",
    "sos.beacon_live": "Transpondeur de Détresse Actif",
    "sos.broadcasting_telemetry": "Transmission de la Télémétrie d'Urgence",
    "sos.transmitting_desk": "Coordonnées satellite en direct transmises au centre d'opérations",
    "sos.beacon_id": "ID de Balise",
    "sos.assigned_unit": "Unité Assignée",
    "sos.sector_role": "Secteur / Rôle",
    "sos.coordinates": "Coordonnées",
    "sos.accuracy_radius": "Rayon de Précision",
    "sos.packet_tx": "Transmissions de Paquets",
    "sos.safety_protocol": "Protocole de Sécurité · Lien d'Urgence",
    "sos.standby": "EN ATTENTE",
    "sos.protocol_desc": "En cas de danger routier critique, de panne ou d'urgence médicale, activez le transpondeur.",
    "sos.conditions_title": "Conditions de Détresse (Optionnel)",
    "sos.hold_warning": "Maintien de 2 secondes requis pour éviter les déclenchements accidentels",
    "sync.radio_mode": "Mode Émetteur-Récepteur Radio",
    "sync.uplink_controller": "Contrôleur de Liaison Montante",
    "sync.auto_adaptive": "Automatique (Adaptatif)",
    "sync.manual_override": "Contrôle Manuel",
    "sync.rtk_uplink": "Liaison Montante RTK en Direct",
    "sync.mesh_network": "Réseau Maillé",
    "sync.airgap_protocol": "Protocole Airgap (Hors Ligne)",
    "sync.outbox_pipeline": "File d'Attente d'Envoi",
    "sync.reports_queued": "Rapports en File d'Attente",
    "sync.outbox_cleared": "Boîte d'Envoi Vide",
    "sync.last_synced": "Dernière synchro",
    "sync.local_cache": "Cache Local IndexedDB",
    "sync.map_sectors": "Secteurs de Carte",
    "sync.reports": "Rapports",
    "sync.breadcrumbs": "Traces GPS",
    "sync.outbox_buffer": "Tampon d'Envoi",
    "sync.total_entries": "entrées totales",
    "sync.empty_outbox": "La boîte d'envoi est vide"
  },
  "de": {
    "nav.home": "Start",
    "nav.map": "Karte",
    "nav.report": "Meldung",
    "nav.sync": "Sync",
    "nav.sos": "SOS",
    "header.ops": "Feldeinsatz",
    "header.live": "Live",
    "header.off": "Offline",
    "home.designated_corridor": "Ausgewiesener Transitkorridor",
    "home.no_route": "Keine Route zugewiesen",
    "home.clearance": "Durchfahrt",
    "home.distance": "Distanz",
    "home.outbox": "Ausgang",
    "home.sector_pass_rate": "Passierquote",
    "home.direct_route": "Direktroute",
    "home.buffered_updates": "Gepufferte Daten",
    "home.synchronized": "Synchronisiert",
    "home.queued": "in Warteschlange",
    "home.engage_navigation": "Navigation starten",
    "home.live_speed": "Tempo",
    "home.altitude": "Barometrische Höhe",
    "home.gnss_stream": "GNSS-Datenstrom",
    "home.transit_estimate": "Fahrzeitschätzung",
    "home.hazards": "Gefahren",
    "home.noted": "gemeldet",
    "home.field_feed": "Feld-Telemetrie-Feed",
    "home.view_all": "Alle ansehen",
    "home.no_hazards": "Keine Gefahren in diesem Sektor",
    "home.synced": "Sync",
    "route.planner_title": "Transitkorridor-Planer",
    "route.planner_sub": "Offline-Routing & Taktische Karten",
    "route.search_placeholder": "Korridor, Depot oder Pass suchen",
    "route.full_map": "Vollbild",
    "route.exit_full": "Beenden",
    "route.verified_hubs": "Verifizierte Hubs",
    "route.recenter_gps": "GPS zentrieren",
    "route.fit_route": "Route anpassen",
    "route.engage_nav": "Route starten",
    "route.calculating": "Route wird berechnet...",
    "route.route_ready": "Route bereit",
    "route.live_results": "Gefundene Orte",
    "report.title": "Feld-Vorfallbericht",
    "report.subtitle": "Echtzeit-Gefahrenfeed",
    "report.active_reporter": "Aktiver Einsatzleiter",
    "report.fetch_gps": "Echte GPS-Position abrufen",
    "report.locating_gps": "Satelliten-GPS-Signal wird gesucht...",
    "report.gps_locked": "Satelliten-GPS erfasst",
    "report.simulated_gps": "Simuliertes GPS aktiv",
    "report.category": "Kategorie",
    "report.severity": "Dringlichkeitsstufe",
    "report.segment": "Straßenabschnitt",
    "report.report_title": "Berichtstitel",
    "report.observations": "Beobachtungen vor Ort",
    "report.broadcast": "Bericht sofort senden",
    "report.offline_save": "Im Ausgang speichern",
    "report.form_tab": "Neuer Bericht",
    "report.history_tab": "Verlauf",
    "sos.title": "Notfall-SOS-Bake",
    "sos.subtitle": "Verschlüsselter Notruf",
    "sos.operator": "Einsatzkraft in Not",
    "sos.hold_prompt": "2 Sekunden gedrückt halten zum Senden",
    "sos.active_status": "SOS-BAKE SENDET NOTRUF",
    "sos.cancel_beacon": "Notruf abbrechen (Fehlalarm)",
    "sos.medical": "Medizinischer Notfall",
    "sos.breakdown": "Fahrzeugpanne",
    "sos.threat": "Hindernis / Bedrohung",
    "sync.title": "Offline-Synchronisationszentrum",
    "sync.subtitle": "Zwischenspeicherung & Übertragung",
    "sync.sync_now": "Jetzt alles synchronisieren",
    "sync.all_synced": "Alle Einträge mit Basis synchronisiert",
    "sync.pending_records": "Einträge im Puffer",
    "sos.beacon_live": "Notfall-Transponder Aktiv",
    "sos.broadcasting_telemetry": "Sende Notfall-Telemetrie",
    "sos.transmitting_desk": "Echtzeit-Satellitenkoordinaten an Einsatzleitung übertragen",
    "sos.beacon_id": "Baken-ID",
    "sos.assigned_unit": "Zugewiesene Einheit",
    "sos.sector_role": "Sektor / Funktion",
    "sos.coordinates": "Koordinaten",
    "sos.accuracy_radius": "Genauigkeitsradius",
    "sos.packet_tx": "Paketübertragungen",
    "sos.safety_protocol": "Sicherheitsprotokoll · Notfallverbindung",
    "sos.standby": "BEREITSCHAFT",
    "sos.protocol_desc": "Aktivieren Sie bei Gefahr, Fahrzeugpanne oder medizinischem Notfall den Notfalltransponder.",
    "sos.conditions_title": "Notfallbedingungen (Optional)",
    "sos.hold_warning": "2 Sekunden gedrückt halten, um versehentliches Auslösen zu verhindern",
    "sync.radio_mode": "Funk-Transceiver-Modus",
    "sync.uplink_controller": "Telemetrie-Uplink-Steuerung",
    "sync.auto_adaptive": "Automatisch (Adaptiv)",
    "sync.manual_override": "Manuelle Übersteuerung",
    "sync.rtk_uplink": "Live-RTK-Uplink",
    "sync.mesh_network": "Mesh-Netzwerk",
    "sync.airgap_protocol": "Airgap-Protokoll (Offline)",
    "sync.outbox_pipeline": "Ausgangs-Pipeline",
    "sync.reports_queued": "Berichte in Warteschlange",
    "sync.outbox_cleared": "Ausgang Geleert",
    "sync.last_synced": "Zuletzt synchronisiert",
    "sync.local_cache": "Lokaler IndexedDB-Cache",
    "sync.map_sectors": "Kartensektoren",
    "sync.reports": "Berichte",
    "sync.breadcrumbs": "GPS-Spur",
    "sync.outbox_buffer": "Ausgangs-Puffer",
    "sync.total_entries": "Einträge gesamt",
    "sync.empty_outbox": "Ausgang ist leer"
  },
  "ar": {
    "nav.home": "الرئيسية",
    "nav.map": "الخريطة",
    "nav.report": "تقرير",
    "nav.sync": "مزامنة",
    "nav.sos": "طوارئ",
    "header.ops": "العمليات الميدانية",
    "header.live": "مباشر",
    "header.off": "غير متصل",
    "home.designated_corridor": "ممر العبور المخصص",
    "home.no_route": "لم يتم تعيين مسار",
    "home.clearance": "التصريح",
    "home.distance": "المسافة",
    "home.outbox": "الصادر",
    "home.sector_pass_rate": "معدل العبور في القطاع",
    "home.direct_route": "المسار المباشر",
    "home.buffered_updates": "تحديثات مخزنة",
    "home.synchronized": "تمت المزامنة",
    "home.queued": "في الانتظار",
    "home.engage_navigation": "بدء ملاحة الممر",
    "home.live_speed": "السرعة المباشرة",
    "home.altitude": "الارتفاع الجوي",
    "home.gnss_stream": "بث بيانات GNSS",
    "home.transit_estimate": "تقدير وقت العبور",
    "home.hazards": "المخاطر",
    "home.noted": "مسجلة",
    "home.field_feed": "بيانات القياس الميدانية",
    "home.view_all": "عرض الكل",
    "home.no_hazards": "لا توجد مخاطر مسجلة في هذا القطاع",
    "home.synced": "متزامن",
    "route.planner_title": "مخطط ممرات العبور",
    "route.planner_sub": "ملاحة بدون اتصال وخرائط تكتيكية",
    "route.search_placeholder": "ابحث عن ممر أو مستودع أو ممر جبلي",
    "route.full_map": "ملء الشاشة",
    "route.exit_full": "خروج",
    "route.verified_hubs": "مراكز لوجستية استراتيجية معتمدة",
    "route.recenter_gps": "إعادة ضبط GPS",
    "route.fit_route": "ملاءمة المسار كامل",
    "route.engage_nav": "بدء الملاحة",
    "route.calculating": "جارٍ حساب المسار...",
    "route.route_ready": "المسار جاهز",
    "route.live_results": "المواقع التي تم العثور عليها",
    "report.title": "تقرير الحوادث الميداني",
    "report.subtitle": "بيانات المخاطر المباشرة",
    "report.active_reporter": "المراسل الميداني الحالي",
    "report.fetch_gps": "تحديد موقع GPS المباشر",
    "report.locating_gps": "جارٍ البحث عن إشارة GPS عبر الأقمار الصناعية...",
    "report.gps_locked": "تم قفل إشارة GPS",
    "report.simulated_gps": "نظام GPS المحاكى نشط",
    "report.category": "فئة الحادث",
    "report.severity": "مستوى الخطورة",
    "report.segment": "قطاع الطريق أو الممر",
    "report.report_title": "عنوان البلاغ",
    "report.observations": "الملاحظات الميدانية / الظروف",
    "report.broadcast": "إرسال البلاغ فوراً",
    "report.offline_save": "حفظ في صندوق الصادر بدون اتصال",
    "report.form_tab": "تقرير جديد",
    "report.history_tab": "السجل الميداني",
    "sos.title": "جهاز استغاثة الطوارئ",
    "sos.subtitle": "بث طوارئ مشفر عالي الأولوية",
    "sos.operator": "مشغل الاستغاثة",
    "sos.hold_prompt": "اضغط باستمرار لمدة ثانيتين لبث نداء الاستغاثة",
    "sos.active_status": "نداء الاستغاثة قيد البث الآن",
    "sos.cancel_beacon": "إلغاء نداء الاستغاثة (إنذار خاطئ)",
    "sos.medical": "أولوية طبية",
    "sos.breakdown": "عطل بالمركبة",
    "sos.threat": "عائق في المسار / تهديد",
    "sync.title": "مركز المزامنة بدون اتصال",
    "sync.subtitle": "تخزين وتمرير بيانات القياس",
    "sync.sync_now": "مزامنة جميع السجلات الآن",
    "sync.all_synced": "تمت مزامنة جميع السجلات مع المركز",
    "sync.pending_records": "سجلات في الانتظار",
    "sos.beacon_live": "جهاز إرسال الاستغاثة نشط",
    "sos.broadcasting_telemetry": "بث القياس عن بُعد للطوارئ",
    "sos.transmitting_desk": "إرسال إحداثيات الأقمار الصناعية الفورية إلى مكتب العمليات",
    "sos.beacon_id": "معرف المنارة",
    "sos.assigned_unit": "الوحدة المعينة",
    "sos.sector_role": "القطاع / الدور",
    "sos.coordinates": "الإحداثيات",
    "sos.accuracy_radius": "نصف قطر الدقة",
    "sos.packet_tx": "إرسال الحزم",
    "sos.safety_protocol": "بروتوكول الأمان · رابط الطوارئ",
    "sos.standby": "في وضع الاستعداد",
    "sos.protocol_desc": "في حالة وجود خطر حرج على الطريق أو عطل في المركبة أو ضائقة طبية، قم بتنشيط جهاز الإرسال.",
    "sos.conditions_title": "ظروف الاستغاثة (اختياري)",
    "sos.hold_warning": "يلزم الضغط لمدة ثانيتين لمنع التنشيط العرضي",
    "sync.radio_mode": "وضع جهاز الإرسال والاستقبال اللاسلكي",
    "sync.uplink_controller": "وحدة التحكم في الارتباط الصاعد للقياس عن بُعد",
    "sync.auto_adaptive": "تلقائي (تكيفي)",
    "sync.manual_override": "تجاوز يدوي",
    "sync.rtk_uplink": "ارتباط RTK مباشر",
    "sync.mesh_network": "شبكة متداخلة (كمون عالي)",
    "sync.airgap_protocol": "بروتوكول العزل التام (بدون إنترنت)",
    "sync.outbox_pipeline": "مسار صندوق الصادر",
    "sync.reports_queued": "تقارير في قائمة الانتظار",
    "sync.outbox_cleared": "تم مسح صندوق الصادر",
    "sync.last_synced": "آخر مزامنة",
    "sync.local_cache": "ذاكرة التخزين المؤقت المحلية IndexedDB",
    "sync.map_sectors": "قطاعات الخريطة",
    "sync.reports": "التقارير",
    "sync.breadcrumbs": "مسار التنقل",
    "sync.outbox_buffer": "مخزن مؤقت لصندوق الصادر",
    "sync.total_entries": "إجمالي الإدخالات",
    "sync.empty_outbox": "صندوق الصادر فارغ"
  },
  "zh": {
    "nav.home": "主页",
    "nav.map": "地图",
    "nav.report": "上报",
    "nav.sync": "同步",
    "nav.sos": "求救",
    "header.ops": "现场行动",
    "header.live": "在线",
    "header.off": "离线",
    "home.designated_corridor": "指定交通走廊",
    "home.no_route": "未分配路线",
    "home.clearance": "通行率",
    "home.distance": "距离",
    "home.outbox": "发件箱",
    "home.sector_pass_rate": "扇区通行成功率",
    "home.direct_route": "直线路线",
    "home.buffered_updates": "待发更新",
    "home.synchronized": "已同步",
    "home.queued": "排队中",
    "home.engage_navigation": "开启路线导航",
    "home.live_speed": "实时速度",
    "home.altitude": "气压海拔",
    "home.gnss_stream": "GNSS遥测流",
    "home.transit_estimate": "预计耗时",
    "home.hazards": "道路危险",
    "home.noted": "项记录",
    "home.field_feed": "现场遥测动态",
    "home.view_all": "查看全部",
    "home.no_hazards": "该扇区未报告危险",
    "home.synced": "已同步",
    "route.planner_title": "交通走廊规划器",
    "route.planner_sub": "高韧性离线路线规划与战术地图",
    "route.search_placeholder": "搜索交通走廊、物流中心或关口",
    "route.full_map": "全屏地图",
    "route.exit_full": "退出全屏",
    "route.verified_hubs": "东北部战略物流枢纽",
    "route.recenter_gps": "GPS居中",
    "route.fit_route": "自适应路线",
    "route.engage_nav": "开始导航",
    "route.calculating": "正在规划路线...",
    "route.route_ready": "路线规划完成",
    "route.live_results": "搜索到的位置",
    "report.title": "现场事件上报",
    "report.subtitle": "实时众包灾情动态",
    "report.active_reporter": "当前上报员",
    "report.fetch_gps": "获取设备实时GPS定位",
    "report.locating_gps": "正在捕获卫星GPS信号...",
    "report.gps_locked": "卫星GPS已锁定",
    "report.simulated_gps": "模拟GPS已激活",
    "report.category": "事件分类",
    "report.severity": "严重程度",
    "report.segment": "道路或走廊路段",
    "report.report_title": "报告标题",
    "report.observations": "现场观察与路况描述",
    "report.broadcast": "立即广播上报事件",
    "report.offline_save": "保存到离线发件箱",
    "report.form_tab": "新建上报",
    "report.history_tab": "历史记录",
    "sos.title": "应急求救应答机",
    "sos.subtitle": "加密高优先级紧急广播",
    "sos.operator": "求救操作员",
    "sos.hold_prompt": "长按2秒发射求救信号",
    "sos.active_status": "求救信标正在广播",
    "sos.cancel_beacon": "取消求救信标（误报解除）",
    "sos.medical": "医疗救援需求",
    "sos.breakdown": "车辆严重损坏",
    "sos.threat": "路线受阻 / 威胁",
    "sync.title": "离线同步中心",
    "sync.subtitle": "存储转发遥测系统",
    "sync.sync_now": "立即同步全部记录",
    "sync.all_synced": "所有数据均已与指挥中心同步",
    "sync.pending_records": "条记录待发送",
    "sos.beacon_live": "遇险应答器实时激活",
    "sos.broadcasting_telemetry": "正在广播紧急遥测数据",
    "sos.transmitting_desk": "实时卫星坐标正在发送至指挥中心",
    "sos.beacon_id": "信标编号",
    "sos.assigned_unit": "分配单位",
    "sos.sector_role": "扇区 / 职务",
    "sos.coordinates": "坐标",
    "sos.accuracy_radius": "精度半径",
    "sos.packet_tx": "数据包传输",
    "sos.safety_protocol": "安全协议 · 应急链路",
    "sos.standby": "待命",
    "sos.protocol_desc": "遇道路严重危险、车辆故障或医疗紧急情况时，请启动应急应答器。",
    "sos.conditions_title": "求救条件（可选）",
    "sos.hold_warning": "按住2秒以防误触启动",
    "sync.radio_mode": "无线电收发模式",
    "sync.uplink_controller": "遥测上行控制器",
    "sync.auto_adaptive": "自动（自适应）",
    "sync.manual_override": "手动控制",
    "sync.rtk_uplink": "实时 RTK 上行",
    "sync.mesh_network": "高延迟 Mesh 网络",
    "sync.airgap_protocol": "物理隔离离线协议",
    "sync.outbox_pipeline": "发件箱管道",
    "sync.reports_queued": "排队报告",
    "sync.outbox_cleared": "发件箱已清空",
    "sync.last_synced": "最后同步",
    "sync.local_cache": "本地 IndexedDB 缓存",
    "sync.map_sectors": "地图区域",
    "sync.reports": "报告",
    "sync.breadcrumbs": "足迹面包屑",
    "sync.outbox_buffer": "发件箱缓冲区",
    "sync.total_entries": "总条目",
    "sync.empty_outbox": "发件箱为空"
  },
  "ja": {
    "nav.home": "ホーム",
    "nav.map": "地図",
    "nav.report": "報告",
    "nav.sync": "同期",
    "nav.sos": "SOS",
    "header.ops": "現場作戦",
    "header.live": "ライブ",
    "header.off": "オフライン",
    "home.designated_corridor": "指定輸送回廊",
    "home.no_route": "ルート未設定",
    "home.clearance": "通行率",
    "home.distance": "距離",
    "home.outbox": "送信トレイ",
    "home.sector_pass_rate": "セクター通過率",
    "home.direct_route": "最短ルート",
    "home.buffered_updates": "バッファ更新",
    "home.synchronized": "同期完了",
    "home.queued": "件待機中",
    "home.engage_navigation": "回廊ナビを開始",
    "home.live_speed": "現在速度",
    "home.altitude": "気圧高度",
    "home.gnss_stream": "GNSSテレメトリ",
    "home.transit_estimate": "予想所要時間",
    "home.hazards": "障害情報",
    "home.noted": "件検出",
    "home.field_feed": "現場テレメトリフィード",
    "home.view_all": "すべて表示",
    "home.no_hazards": "危険箇所なし",
    "home.synced": "同期済",
    "route.planner_title": "輸送回廊プランナー",
    "route.planner_sub": "オフライン高耐性ナビ＆タクティカルマップ",
    "route.search_placeholder": "回廊・拠点・峠を検索",
    "route.full_map": "全画面表示",
    "route.exit_full": "全画面終了",
    "route.verified_hubs": "戦略的拠点",
    "route.recenter_gps": "GPSリセット",
    "route.fit_route": "全体表示",
    "route.engage_nav": "ナビ開始",
    "route.calculating": "ルート計算中...",
    "route.route_ready": "ルート設定完了",
    "route.live_results": "検索結果",
    "report.title": "現場ハザード報告",
    "report.subtitle": "リアルタイム障害フィード",
    "report.active_reporter": "報告オペレーター",
    "report.fetch_gps": "リアルタイムGPS取得",
    "report.locating_gps": "衛星GPS信号捕捉中...",
    "report.gps_locked": "衛星GPSロック完了",
    "report.simulated_gps": "シミュレーションGPS稼働中",
    "report.category": "事象カテゴリ",
    "report.severity": "重要度",
    "report.segment": "対象道路・区間",
    "report.report_title": "報告タイトル",
    "report.observations": "現場状況・詳細",
    "report.broadcast": "直ちに緊急報告を送信",
    "report.offline_save": "オフライン保存",
    "report.form_tab": "新規報告",
    "report.history_tab": "履歴",
    "sos.title": "遭難信号トランスポンダ",
    "sos.subtitle": "暗号化高優先緊急ブロードキャスト",
    "sos.operator": "発信オペレーター",
    "sos.hold_prompt": "2秒長押しでSOS発信",
    "sos.active_status": "遭難信号発信中",
    "sos.cancel_beacon": "遭難信号を解除（誤報）",
    "sos.medical": "医療救護要請",
    "sos.breakdown": "車両故障",
    "sos.threat": "進路障害・脅威",
    "sync.title": "オフライン同期センター",
    "sync.subtitle": "ストア＆フォワードテレメトリ",
    "sync.sync_now": "全レコードを今すぐ同期",
    "sync.all_synced": "ベースステーションと同期完了",
    "sync.pending_records": "件の未送信レコード",
    "sos.beacon_live": "緊急遭難トランスポンダー作動中",
    "sos.broadcasting_telemetry": "緊急テレメトリをブロードキャスト中",
    "sos.transmitting_desk": "リアルタイム衛星座標が運用本部に送信されています",
    "sos.beacon_id": "ビーコンID",
    "sos.assigned_unit": "配属部隊",
    "sos.sector_role": "セクター / 役割",
    "sos.coordinates": "座標",
    "sos.accuracy_radius": "精度半径",
    "sos.packet_tx": "パケット送信",
    "sos.safety_protocol": "安全プロトコル · 緊急リンク",
    "sos.standby": "待機中",
    "sos.protocol_desc": "道路の危険、車両の故障、または医療上の緊急事態が発生した場合は、緊急トランスポンダーを作動させてください。",
    "sos.conditions_title": "遭難状況（任意）",
    "sos.hold_warning": "誤作動防止のため2秒間長押ししてください",
    "sync.radio_mode": "無線送受信モード",
    "sync.uplink_controller": "テレメトリアップリンクコントローラー",
    "sync.auto_adaptive": "自動（適応型）",
    "sync.manual_override": "手動オーバーライド",
    "sync.rtk_uplink": "ライブ RTK アップリンク",
    "sync.mesh_network": "高遅延メッシュネットワーク",
    "sync.airgap_protocol": "エアギャップ（完全オフライン）",
    "sync.outbox_pipeline": "送信トレイパイプライン",
    "sync.reports_queued": "待機中のレポート",
    "sync.outbox_cleared": "送信トレイは空です",
    "sync.last_synced": "最終同期",
    "sync.local_cache": "ローカル IndexedDB キャッシュ",
    "sync.map_sectors": "マップセクター",
    "sync.reports": "報告書",
    "sync.breadcrumbs": "移動軌跡",
    "sync.outbox_buffer": "送信バッファ",
    "sync.total_entries": "合計エントリー",
    "sync.empty_outbox": "送信トレイは空です"
  },
  "ru": {
    "nav.home": "Главная",
    "nav.map": "Карта",
    "nav.report": "Отчет",
    "nav.sync": "Синхр",
    "nav.sos": "SOS",
    "header.ops": "Полевые операции",
    "header.live": "В сети",
    "header.off": "Офлайн",
    "home.designated_corridor": "Назначенный транспортный коридор",
    "home.no_route": "Маршрут не назначен",
    "home.clearance": "Проходимость",
    "home.distance": "Дистанция",
    "home.outbox": "Исходящие",
    "home.sector_pass_rate": "Проходимость сектора",
    "home.direct_route": "Прямой маршрут",
    "home.buffered_updates": "Буферизованные данные",
    "home.synchronized": "Синхронизировано",
    "home.queued": "в очереди",
    "home.engage_navigation": "Начать навигацию по коридору",
    "home.live_speed": "Текущая скорость",
    "home.altitude": "Барометрическая высота",
    "home.gnss_stream": "GNSS телеметрия",
    "home.transit_estimate": "Расчетное время",
    "home.hazards": "Опасности",
    "home.noted": "зафиксировано",
    "home.field_feed": "Полевая лента телеметрии",
    "home.view_all": "Смотреть все",
    "home.no_hazards": "Опасностей в секторе нет",
    "home.synced": "Синхр",
    "route.planner_title": "Планировщик коридоров",
    "route.planner_sub": "Офлайн маршрутизация и карты",
    "route.search_placeholder": "Поиск коридора, базы или перевала",
    "route.full_map": "Полный экран",
    "route.exit_full": "Выйти",
    "route.verified_hubs": "Стратегические узлы",
    "route.recenter_gps": "Центрировать GPS",
    "route.fit_route": "Показать маршрут",
    "route.engage_nav": "Начать маршрут",
    "route.calculating": "Расчет маршрута...",
    "route.route_ready": "Маршрут готов",
    "route.live_results": "Найденные места",
    "report.title": "Полевой отчет об инциденте",
    "report.subtitle": "Лента дорожных угроз в реальном времени",
    "report.active_reporter": "Активный оператор",
    "report.fetch_gps": "Получить реальный GPS",
    "report.locating_gps": "Поиск спутникового GPS...",
    "report.gps_locked": "Спутниковый GPS захвачен",
    "report.simulated_gps": "Симулированный GPS активен",
    "report.category": "Категория инцидента",
    "report.severity": "Уровень опасности",
    "report.segment": "Участок дороги / коридора",
    "report.report_title": "Заголовок отчета",
    "report.observations": "Полевые наблюдения",
    "report.broadcast": "Немедленно передать отчет",
    "report.offline_save": "Сохранить в исходящие",
    "report.form_tab": "Новый отчет",
    "report.history_tab": "История",
    "sos.title": "Аварийный транспондер SOS",
    "sos.subtitle": "Приоритетная зашифрованная трансляция",
    "sos.operator": "Оператор в беде",
    "sos.hold_prompt": "Удерживайте 2 сек для передачи SOS",
    "sos.active_status": "АВАРИЙНЫЙ СИГНАЛ ПЕРЕДАЕТСЯ",
    "sos.cancel_beacon": "Отменить сигнал (Ложная тревога)",
    "sos.medical": "Медицинская помощь",
    "sos.breakdown": "Поломка транспорта",
    "sos.threat": "Препятствие / Угроза",
    "sync.title": "Центр офлайн синхронизации",
    "sync.subtitle": "Буферизация и передача данных",
    "sync.sync_now": "Синхронизировать сейчас",
    "sync.all_synced": "Все данные синхронизированы",
    "sync.pending_records": "записей в буфере",
    "sos.beacon_live": "Аварийный радиомаяк активен",
    "sos.broadcasting_telemetry": "Трансляция экстренной телеметрии",
    "sos.transmitting_desk": "Передача спутниковых координат на пульт управления",
    "sos.beacon_id": "ID Маяка",
    "sos.assigned_unit": "Назначенное подразделение",
    "sos.sector_role": "Сектор / Должность",
    "sos.coordinates": "Координаты",
    "sos.accuracy_radius": "Радиус точности",
    "sos.packet_tx": "Передачи пакетов",
    "sos.safety_protocol": "Протокол безопасности · Аварийный канал",
    "sos.standby": "ОЖИДАНИЕ",
    "sos.protocol_desc": "При критической дорожной опасности, поломке или медицинской помощи включите аварийный маяк.",
    "sos.conditions_title": "Условия бедствия (необязательно)",
    "sos.hold_warning": "Удерживайте 2 секунды для предотвращения случайного срабатывания",
    "sync.radio_mode": "Режим радиоприемопередатчика",
    "sync.uplink_controller": "Контроллер аплинка телеметрии",
    "sync.auto_adaptive": "Авто (адаптивный)",
    "sync.manual_override": "Ручное управление",
    "sync.rtk_uplink": "Прямой RTK аплинк",
    "sync.mesh_network": "Mesh-сеть с задержкой",
    "sync.airgap_protocol": "Протокол изоляции (Офлайн)",
    "sync.outbox_pipeline": "Очередь исходящих",
    "sync.reports_queued": "Отчетов в очереди",
    "sync.outbox_cleared": "Исходящие отправлены",
    "sync.last_synced": "Последняя синхронизация",
    "sync.local_cache": "Локальный кэш IndexedDB",
    "sync.map_sectors": "Сектора карты",
    "sync.reports": "Отчеты",
    "sync.breadcrumbs": "След маршрута",
    "sync.outbox_buffer": "Буфер исходящих",
    "sync.total_entries": "всего записей",
    "sync.empty_outbox": "В исходящих ничего нет"
  },
  "pt": {
    "nav.home": "Início",
    "nav.map": "Mapa",
    "nav.report": "Relatar",
    "nav.sync": "Sinc",
    "nav.sos": "SOS",
    "header.ops": "Operações",
    "header.live": "Ao vivo",
    "header.off": "Offline",
    "home.designated_corridor": "Corredor de Trânsito Designado",
    "home.no_route": "Nenhuma rota atribuída",
    "home.clearance": "Liberação",
    "home.distance": "Distância",
    "home.outbox": "Saída",
    "home.sector_pass_rate": "Taxa de passagem do setor",
    "home.direct_route": "Rota direta",
    "home.buffered_updates": "Atualizações no buffer",
    "home.synchronized": "Sincronizado",
    "home.queued": "na fila",
    "home.engage_navigation": "Iniciar Navegação do Corredor",
    "home.live_speed": "Velocidade",
    "home.altitude": "Altitude Barométrica",
    "home.gnss_stream": "Fluxo GNSS",
    "home.transit_estimate": "Estimativa de Trânsito",
    "home.hazards": "Perigos",
    "home.noted": "anotados",
    "home.field_feed": "Feed de Telemetria de Campo",
    "home.view_all": "Ver tudo",
    "home.no_hazards": "Nenhum perigo neste setor",
    "home.synced": "Sinc",
    "route.planner_title": "Planejador de Corredor",
    "route.planner_sub": "Roteamento Offline & Mapas Táticos",
    "route.search_placeholder": "Pesquisar Corredor, Terminal ou Passo",
    "route.full_map": "Mapa Completo",
    "route.exit_full": "Sair",
    "route.verified_hubs": "Centros Logísticos Estratégicos",
    "route.recenter_gps": "Recentralizar GPS",
    "route.fit_route": "Ajustar Rota",
    "route.engage_nav": "Iniciar Navegação",
    "route.calculating": "Calculando rota...",
    "route.route_ready": "Rota Pronta",
    "route.live_results": "Locais Encontrados",
    "report.title": "Relatório de Incidente de Campo",
    "report.subtitle": "Feed de perigos em tempo real",
    "report.active_reporter": "Operador de Campo",
    "report.fetch_gps": "Obter GPS em Tempo Real",
    "report.locating_gps": "Buscando sinal GPS do satélite...",
    "report.gps_locked": "GPS do Satélite Travado",
    "report.simulated_gps": "GPS simulado ativo",
    "report.category": "Categoria do Incidente",
    "report.severity": "Nível de Gravidade",
    "report.segment": "Segmento de Estrada / Corredor",
    "report.report_title": "Título do Relatório",
    "report.observations": "Observações de Campo",
    "report.broadcast": "Transmitir Relatório Agora",
    "report.offline_save": "Salvar na Caixa de Saída Offline",
    "report.form_tab": "Novo Relatório",
    "report.history_tab": "Histórico",
    "sos.title": "Transponder de Emergência SOS",
    "sos.subtitle": "Transmissão de Emergência Criptografada",
    "sos.operator": "Operador em Emergência",
    "sos.hold_prompt": "Segure por 2 segundos para transmitir SOS",
    "sos.active_status": "SINAL DE SOCORRO EM TRANSMISSÃO",
    "sos.cancel_beacon": "Cancelar Transmissão (Alarme Falso)",
    "sos.medical": "Prioridade Médica",
    "sos.breakdown": "Veículo Avariado",
    "sos.threat": "Obstáculo na Rota / Ameaça",
    "sync.title": "Centro de Sincronização Offline",
    "sync.subtitle": "Telemetria Store-and-Forward",
    "sync.sync_now": "Sincronizar Tudo Agora",
    "sync.all_synced": "Todos os registros sincronizados com a base",
    "sync.pending_records": "registros no buffer",
    "sos.beacon_live": "Transponder de Emergência Ativo",
    "sos.broadcasting_telemetry": "Transmitindo Telemetria de Emergência",
    "sos.transmitting_desk": "Coordenadas de satélite em tempo real transmitidas para a central",
    "sos.beacon_id": "ID do Sinalizador",
    "sos.assigned_unit": "Unidade Designada",
    "sos.sector_role": "Setor / Função",
    "sos.coordinates": "Coordenadas",
    "sos.accuracy_radius": "Raio de Precisão",
    "sos.packet_tx": "Transmissões de Pacotes",
    "sos.safety_protocol": "Protocolo de Segurança · Link de Emergência",
    "sos.standby": "EM ESPERA",
    "sos.protocol_desc": "Em caso de perigo crítico na via, pane no veículo ou emergência médica, acione o transponder.",
    "sos.conditions_title": "Condições de Emergência (Opcional)",
    "sos.hold_warning": "Segure por 2 segundos para evitar acionamentos acidentais",
    "sync.radio_mode": "Modo Transceptor de Rádio",
    "sync.uplink_controller": "Controlador de Uplink de Telemetria",
    "sync.auto_adaptive": "Automático (Adaptativo)",
    "sync.manual_override": "Controle Manual",
    "sync.rtk_uplink": "Uplink RTK em Tempo Real",
    "sync.mesh_network": "Rede Mesh (Alta Latência)",
    "sync.airgap_protocol": "Protocolo Airgap (Offline)",
    "sync.outbox_pipeline": "Fila de Saída",
    "sync.reports_queued": "Relatórios na Fila",
    "sync.outbox_cleared": "Caixa de Saída Limpa",
    "sync.last_synced": "Última sincronização",
    "sync.local_cache": "Cache Local IndexedDB",
    "sync.map_sectors": "Setores do Mapa",
    "sync.reports": "Relatórios",
    "sync.breadcrumbs": "Trilha GPS",
    "sync.outbox_buffer": "Buffer de Saída",
    "sync.total_entries": "entradas no total",
    "sync.empty_outbox": "A caixa de saída está vazia"
  }
};

interface LanguageContextType {
  language: SupportedLanguage;
  currentLanguageInfo: LanguageInfo;
  setLanguage: (lang: SupportedLanguage) => void;
  t: (key: string) => string;
  languages: LanguageInfo[];
  northeastLanguages: LanguageInfo[];
  globalLanguages: LanguageInfo[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<SupportedLanguage>(() => {
    try {
      const saved = localStorage.getItem('tactical_app_lang') as SupportedLanguage;
      if (saved && SUPPORTED_LANGUAGES.some(l => l.code === saved)) {
        return saved;
      }
    } catch {}
    return 'en';
  });

  const setLanguage = (lang: SupportedLanguage) => {
    setLanguageState(lang);
    try {
      localStorage.setItem('tactical_app_lang', lang);
    } catch {}
  };

  const t = (key: string): string => {
    const dict = TRANSLATIONS[language];
    if (dict && dict[key]) return dict[key];
    const enDict = TRANSLATIONS.en;
    if (enDict && enDict[key]) return enDict[key];
    return key;
  };

  const currentLanguageInfo = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[10]; // English
  const northeastLanguages = SUPPORTED_LANGUAGES.filter(l => l.category === 'northeast');
  const globalLanguages = SUPPORTED_LANGUAGES.filter(l => l.category === 'global');

  return (
    <LanguageContext.Provider value={{
      language,
      currentLanguageInfo,
      setLanguage,
      t,
      languages: SUPPORTED_LANGUAGES,
      northeastLanguages,
      globalLanguages,
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
